#!/bin/bash
set -u
set -e

# Builds and installs necessary Haskell programs/libraries.
# Assumes you're not using Cabal sandboxes.

cabal install alex happy
cabal install c2hs

# Install build program
cd build
cabal install
cd ..
