#!/bin/bash
set -u
set -e

wget -O sox-14.4.1.tar.gz http://sourceforge.net/projects/sox/files/sox/14.4.1/sox-14.4.1.tar.gz/download
tar -xvzf sox-14.4.1.tar.gz
cd sox-14.4.1
./configure
make -s
sudo make install

# refresh dynamic library cache
sudo /sbin/ldconfig
