#!/usr/bin/env ruby

require 'fileutils'

test_dir = File.expand_path( File.dirname(__FILE__) )
onyxite_min = ENV['ONYXITE_MIN']
onyxite_min = [nil, ''].include?(onyxite_min) ? 0 : onyxite_min.to_i
onyxite_max = ENV['ONYXITE_MAX']
onyxite_max = [nil, ''].include?(onyxite_max) ? 9999 : onyxite_max.to_i

Dir['*/*/README.md'].sort.each_with_index do |readme, i|
  songdir = File.dirname readme

  next if i < onyxite_min
  next if i > onyxite_max
  next unless File.file? "#{songdir}/song.yml"

  puts ">> Building #{songdir}"
  FileUtils.cd songdir

  system 'onyxbuild gen/album/2p/magma/magma.rbproj'
  dummy_length = `#{test_dir}/dummy-time gen/album/2p/magma/magma.rbproj`.to_i
  puts "Making a dummy audio file of length #{dummy_length} seconds."
  system "sox -n audio-album.wav trim 0 #{dummy_length}"
  system "cp audio-album.wav audio-this.wav"
  system "sox -n audio-next.wav trim 0 1:00"

  system "onyxbuild gen/album/2p/magma.rba"

  system "rm -rf gen"
  system "rm audio-album.wav audio-this.wav audio-next.wav"
  FileUtils.cd '../..'
end
