#!/bin/bash
set -u
set -e

TEST_DIR=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

for readme in */*/README.md; do
  if [ $readme = dream-theater/erotomania/README.md ]; then
    continue
  fi
  if [ ! -f `dirname $readme`/song.yml ]; then
    continue
  fi
  echo ">> Building" `dirname $readme`
  cd `dirname $readme`

  onyxbuild gen/album/2p/magma/magma.rbproj
  DUMMY_LENGTH=$($TEST_DIR/dummy-time gen/album/2p/magma/magma.rbproj)
  echo "Making a dummy audio file of length $DUMMY_LENGTH seconds."
  sox -n audio-album.wav trim 0 $DUMMY_LENGTH
  cp audio-album.wav audio-this.wav
  sox -n audio-next.wav trim 0 1:00

  onyxbuild gen/album/2p/magma.rba

  rm -rf gen
  rm audio-album.wav audio-this.wav audio-next.wav
  cd ../..
done
