#!/usr/bin/env ruby

require 'fileutils'
require_relative '../scripts/common'

test_dir = File.expand_path( File.dirname(__FILE__) )
onyxite_min = ENV['ONYXITE_MIN']
onyxite_min = [nil, ''].include?(onyxite_min) ? 0 : onyxite_min.to_i
onyxite_max = ENV['ONYXITE_MAX']
onyxite_max = [nil, ''].include?(onyxite_max) ? 9999 : onyxite_max.to_i

Dir['songs/*/*/song.yml'].sort.each_with_index do |yaml_file, i|
  songdir = File.dirname yaml_file
  yaml = load_yaml_tree yaml_file
  next unless yaml.fetch('published', true)

  next if i < onyxite_min
  next if i > onyxite_max

  puts ">> Building #{songdir}"
  Dir.chdir(songdir) do
    # system_ 'onyx build gen/plan/album/2p/magma/magma.rbproj'
    # dummy_length = `#{test_dir}/dummy-time gen/album/2p/magma/magma.rbproj`.to_i
    # puts "Making a dummy audio file of length #{dummy_length} seconds."
    # system_ "sox -n audio-album.wav trim 0 #{dummy_length} rate 44100"
    # system_ "sox -n audio-next.wav trim 0 1:00 rate 44100"

    # system_ "onyx build gen/plan/album/2p/magma.rba"

    # system_ "rm -rf gen"
    # system_ "rm audio-album.wav audio-next.wav"
  end
end
