#!/bin/bash
set -e
set -u

case $(uname) in
  MINGW* )
    DEFAULT_BIN_DIR="$HOME/Appdata/Roaming/local/bin"
    ;;
  * )
    DEFAULT_BIN_DIR="$HOME/.local/bin"
esac
BIN_DIR="${1:-$DEFAULT_BIN_DIR}"
INSTALL_DIR="$BIN_DIR/onyx-files"

rm -rf "$INSTALL_DIR"
mkdir "$INSTALL_DIR"
stack exec which onyx | xargs -I{} cp {} "$INSTALL_DIR/onyx"
cp -R resources "$INSTALL_DIR/onyx-resources"
cp -R resources-cli/* "$INSTALL_DIR/onyx-resources/"
case $(uname) in
  MINGW* )
    cp dependencies/root/bin/*.dll "$INSTALL_DIR"
    # this needs to be /mingw64 in stack's msys2
    stack exec -- bash -c "cp /mingw64/bin/*.dll $INSTALL_DIR"
    ;;
  * )
    cp -R dependencies/root/lib "$INSTALL_DIR/lib"
    rm "$INSTALL_DIR"/lib/*.a
esac
rm -rf "$BIN_DIR/onyx"
cp run-cli "$BIN_DIR/onyx"
