#!/bin/bash
set -e
set -u

case $(uname) in
  Linux )
    echo "linux detected"
    if which pacman > /dev/null; then
      echo "arch detected"
      pacman -Sy rubberband mpg123 openal \
        cmake autogen autoconf libtool pkg-config nasm unzip
      # TODO finish
    elif which apt-get > /dev/null; then
      echo "debian/ubuntu detected"
      apt-get -y update
      apt-get -y install build-essential cmake autogen autoconf libtool \
        libtool-bin pkg-config gettext nasm unzip libx11-dev \
        libxft-dev libgl-dev libxext-dev libglu-dev libjack-dev libpulse-dev \
        libasound2-dev libbz2-dev libmpg123-dev librubberband-dev libopenal-dev
      case $(cat /etc/issue) in
        *16\.04* )
          # don't need to do anything for the docker version
          ;;
        * )
          apt-get -y install python-is-python3
      esac
      # when we use sdl2, maybe add: libudev dbus ibus
    else
      echo "unknown"
      exit 1
    fi
    ;;
  MINGW* )
    echo "windows detected"
    # for some reason you need "mingw-w64-x86_64-pkg-config" for haskell to use,
    # but just "pkg-config" so libsndfile configures right (seeing ogg/vorbis/flac/opus)
    stack exec -- pacman -Sy mingw-w64-x86_64-pkg-config pkg-config \
      mingw-w64-x86_64-openal mingw-w64-x86_64-rubberband \
      mingw-w64-x86_64-mpg123 wget tar unzip zip man autoconf \
      automake nasm make libtool autogen python
    ;;
  Darwin )
    brew install autoconf automake dylibbundler m4 mpg123 openal-soft nasm pkg-config rubberband libtool autogen
    # brew caveat mentions adding openal-soft to PKG_CONFIG_PATH,
    # instead we'll hack it like so :)
    ln -f -s /usr/local/opt/openal-soft/lib/pkgconfig/openal.pc /usr/local/lib/pkgconfig/openal.pc
    ;;
  * )
    echo "unknown"
    exit 1
esac
