title = A Rite of Passage
package = ariteofpassage
cover-name = black-clouds-silver-linings
number = 2
album-pad = 4.656

include ../../make/config/drums.mk

# TODO: BCSL deluxe edition stems, will require heavy remixing
