title = Voices
jammit-title = A Mind Beside Itself II. Voices
package = voices
cover-name = awake
number = 5
jammit-trim = 3.183
jammit-fadein = 0.477
jammit-pad = 2.877
album-fadein = 0.538
album-pad = 2.893

include ../../make/config/drums.mk
