title = Blind Faith
package = blindfaith
cover-name = six-degrees-of-inner-turbulence
number = 2
album-trim = 10.991
album-fadein = 5.673
album-cutoff = 9:58.000
# sneaking under that Harmonix cutoff
album-fadeout = 5.200

include ../../make/config/drums.mk
