.PHONY: build

build:
	./build.rb Machines 2.370 7.790
	./build.rb Cascades 2.543 6.389
	./build.rb Air 2.343 6.510
	./build.rb Flux 2.936 7.476
	./build.rb RAAR 4.073 6.795
	./build.rb Further 3.835 7.815
