title = In the Presence of Enemies, Pt. 1
package = itpoept1
cover-name = systematic-chaos
number = 1
album-pad = 4.637
album-cutoff = 8:57.302
album-fadeout = 2.75

include ../../make/config/drums.mk
