{-# LANGUAGE OverloadedStrings #-}
module Onyx.Sections.GH2
( gh2Sections
) where

import qualified Data.Text as T

gh2Sections :: [(T.Text, T.Text)]
gh2Sections =
  [ ("intro", "Intro")
  , ("intro_a", "Intro a")
  , ("intro_b", "Intro b")
  , ("intro_c", "Intro c")
  , ("vocal_intro", "Vocal intro")
  , ("gtr_intro", "Gtr intro")
  , ("gtr_intro_a", "Gtr intro a")
  , ("gtr_intro_b", "Gtr intro b")
  , ("gtr_intro_c", "Gtr intro c")
  , ("gtr_intro_d", "Gtr intro d")
  , ("gtr_intro_e", "Gtr intro e")
  , ("intro_riff", "Intro riff")
  , ("bass_intro", "Bass intro")
  , ("noise_intro", "Noise intro")
  , ("gtr_enters", "Gtr enters")
  , ("rhy_enters", "Gtr2 enters")
  , ("bass_enters", "Bass enters")
  , ("band_enters", "Band enters")
  , ("kick_it", "Kick It!")
  , ("quiet_intro", "Quiet intro")
  , ("verse_1", "Verse 1")
  , ("verse_1a", "Verse 1a")
  , ("verse_1b", "Verse 1b")
  , ("verse_1c", "Verse 1c")
  , ("verse_1d", "Verse 1d")
  , ("verse_1e", "Verse 1e")
  , ("verse_1f", "Verse 1f")
  , ("verse_2", "Verse 2")
  , ("verse_2a", "Verse 2a")
  , ("verse_2b", "Verse 2b")
  , ("verse_2c", "Verse 2c")
  , ("verse_2d", "Verse 2d")
  , ("verse_2e", "Verse 2e")
  , ("verse_2f", "Verse 2f")
  , ("verse_3", "Verse 3")
  , ("verse_3a", "Verse 3a")
  , ("verse_3b", "Verse 3b")
  , ("verse_3c", "Verse 3c")
  , ("verse_3d", "Verse 3d")
  , ("verse_3e", "Verse 3e")
  , ("verse_3f", "Verse 3f")
  , ("verse_4", "Verse 4")
  , ("verse_4a", "Verse 4a")
  , ("verse_4b", "Verse 4b")
  , ("verse_4c", "Verse 4c")
  , ("verse_4d", "Verse 4d")
  , ("verse_5", "Verse 5")
  , ("verse_5a", "Verse 5a")
  , ("verse_5b", "Verse 5b")
  , ("verse_5c", "Verse 5c")
  , ("verse_5d", "Verse 5d")
  , ("chorus", "Chorus")
  , ("chorus_1", "Chorus 1")
  , ("chorus_1a", "Chorus 1a")
  , ("chorus_1b", "Chorus 1b")
  , ("chorus_1c", "Chorus 1c")
  , ("chorus_1d", "Chorus 1d")
  , ("chorus_2", "Chorus 2")
  , ("chorus_2a", "Chorus 2a")
  , ("chorus_2b", "Chorus 2b")
  , ("chorus_2c", "Chorus 2c")
  , ("chorus_3", "Chorus 3")
  , ("chorus_3a", "Chorus 3a")
  , ("chorus_3b", "Chorus 3b")
  , ("chorus_3c", "Chorus 3c")
  , ("chorus_4", "Chorus 4")
  , ("chorus_4a", "Chorus 4a")
  , ("chorus_4b", "Chorus 4b")
  , ("chorus_4c", "Chorus 4c")
  , ("chorus_5", "Chorus 5")
  , ("chorus_5a", "Chorus 5a")
  , ("chorus_5b", "Chorus 5b")
  , ("chorus_5c", "Chorus 5c")
  , ("gtr_solo", "Gtr solo")
  , ("gtr_solo_a", "Gtr solo a")
  , ("gtr_solo_b", "Gtr solo b")
  , ("gtr_solo_c", "Gtr solo c")
  , ("gtr_solo_d", "Gtr solo d")
  , ("gtr_solo_e", "Gtr solo e")
  , ("gtr_solo_f", "Gtr solo f")
  , ("gtr_solo_g", "Gtr solo g")
  , ("gtr_solo_h", "Gtr solo h")
  , ("gtr_solo_i", "Gtr solo i")
  , ("gtr_solo_j", "Gtr solo j")
  , ("gtr_solo_k", "Gtr solo k")
  , ("gtr_solo_l", "Gtr solo l")
  , ("gtr_solo_m", "Gtr solo m")
  , ("gtr_solo_n", "Gtr solo n")
  , ("gtr_solo_o", "Gtr solo o")
  , ("gtr_solo_p", "Gtr solo p")
  , ("gtr_solo_q", "Gtr solo q")
  , ("gtr_solo_r", "Gtr solo r")
  , ("gtr_solo_s", "Gtr solo s")
  , ("gtr_solo_1", "Gtr solo 1")
  , ("gtr_solo_1a", "Gtr solo 1a")
  , ("gtr_solo_1b", "Gtr solo 1b")
  , ("gtr_solo_1c", "Gtr solo 1c")
  , ("gtr_solo_1d", "Gtr solo 1d")
  , ("gtr_solo_1e", "Gtr solo 1e")
  , ("gtr_solo_2", "Gtr solo 2")
  , ("gtr_solo_2a", "Gtr solo 2a")
  , ("gtr_solo_2b", "Gtr solo 2b")
  , ("gtr_solo_2c", "Gtr solo 2c")
  , ("gtr_solo_2d", "Gtr solo 2d")
  , ("gtr_solo_2e", "Gtr solo 2e")
  , ("gtr_solo_2f", "Gtr solo 2f")
  , ("gtr_solo_2g", "Gtr solo 2g")
  , ("gtr_solo_3", "Gtr solo 3")
  , ("gtr_solo_3a", "Gtr solo 3a")
  , ("gtr_solo_3b", "Gtr solo 3b")
  , ("gtr_solo_3c", "Gtr solo 3c")
  , ("gtr_solo_4", "Gtr solo 4")
  , ("gtr_solo_4a", "Gtr solo 4a")
  , ("gtr_solo_4b", "Gtr solo 4b")
  , ("gtr_solo_5", "Gtr solo 5")
  , ("gtr_solo_6", "Gtr solo 6")
  , ("gtr_solo_7", "Gtr solo 7!")
  , ("gtr_solo_8", "Gtr solo 8!!")
  , ("gtr_solo_9", "Gtr solo 9!!!")
  , ("drum_solo", "Drum solo")
  , ("drum_solo_1", "Drum solo 1")
  , ("drum_solo_2", "Drum solo 2")
  , ("drum_solo_3", "Drum solo 3")
  , ("bass_solo", "Bass solo")
  , ("bass_solo_1", "Bass solo 1")
  , ("bass_solo_2", "Bass solo 2")
  , ("bass_solo_3", "Bass solo 3")
  , ("organ_solo", "Organ solo")
  , ("noise_solo", "Noise solo")
  , ("trill_me_1", "Trill me!")
  , ("trill_me_2", "Trill me!!")
  , ("ah_ah_1", "Ah ah!")
  , ("ah_ah_2", "Ah ah!!")
  , ("trogdor_1", "TROGDOR!")
  , ("trogdor_2", "TROGDOR!!")
  , ("trogdor_3", "TROGDOR!!!")
  , ("trc", "T-R-C!!")
  , ("slide_solo_1", "Slide solo 1")
  , ("slide_solo_2", "Slide solo 2")
  , ("fast_part", "Fast part")
  , ("gtr_lead_1", "Gtr lead 1")
  , ("gtr_lead_2", "Gtr lead 2")
  , ("gtr_lead_3", "Gtr lead 3")
  , ("speed_picking", "Fast picking")
  , ("slow_hvy", "Slow part")
  , ("bridge", "Bridge")
  , ("bridge_a", "Bridge a")
  , ("bridge_b", "Bridge b")
  , ("bridge_c", "Bridge c")
  , ("bridge_d", "Bridge d")
  , ("bridge_1", "Bridge 1")
  , ("bridge_1a", "Bridge 1a")
  , ("bridge_1b", "Bridge 1b")
  , ("bridge_2", "Bridge 2")
  , ("bridge_2a", "Bridge 2a")
  , ("bridge_2b", "Bridge 2b")
  , ("break", "Break")
  , ("break_1", "Break 1")
  , ("break_2", "Break 2")
  , ("breakdown", "Breakdown")
  , ("jam", "Jam")
  , ("gtr_break", "Gtr break")
  , ("gtr_break_1", "Gtr break 1")
  , ("gtr_break_2", "Gtr break 2")
  , ("gtr_break_3", "Gtr break 3")
  , ("gtr_break_4", "Gtr break 4")
  , ("gtr_fill", "Gtr fill")
  , ("gtr_fills", "Gtr fills")
  , ("gtr_hook", "Gtr hook")
  , ("gtr_hook_1", "Gtr hook 1")
  , ("gtr_hook_2", "Gtr hook 2")
  , ("gtr_hook_3", "Gtr hook 3")
  , ("vocal_break", "Vocal break")
  , ("noise_build", "Noise build")
  , ("release", "Release")
  , ("melody_1", "Melody 1")
  , ("melody_2", "Melody 2")
  , ("lo_melody", "Low melody")
  , ("gtr_mel_1", "Melody 1")
  , ("gtr_mel_2", "Melody 2")
  , ("gtr_mel_3", "Melody 3")
  , ("speedup", "Speed up")
  , ("main_riff_1", "Main riff 1")
  , ("main_riff_2", "Main riff 2")
  , ("main_riff_3", "Main riff 3")
  , ("main_riff_4", "Main riff 4")
  , ("main_riff_5", "Main riff 5")
  , ("main_riff_6", "Main riff 6")
  , ("main_riff_7", "Main riff 7")
  , ("high_gtr_1", "High gtr 1")
  , ("high_gtr_2", "High gtr 2")
  , ("high_gtr_3", "High gtr 3")
  , ("high_gtr_4", "High gtr 4")
  , ("verse_riff", "Verse riff")
  , ("chorus_riff", "Chorus riff")
  , ("gtr_riff_1", "Gtr riff 1")
  , ("gtr_riff_2", "Gtr riff 2")
  , ("big_riff_1", "Big riff 1")
  , ("big_riff_2", "Big riff 2")
  , ("bigger_riff", "Bigger riff")
  , ("swing_riff_1", "Swing riff 1")
  , ("swing_riff_2", "Swing riff 2")
  , ("swing_riff_3", "Swing riff 3")
  , ("swing_riff_4", "Swing riff 4")
  , ("chunky_riff_1", "Chunk riff 1")
  , ("chunky_riff_2", "Chunk riff 2")
  , ("odd_riff_1", "Odd riff 1")
  , ("odd_riff_2", "Odd riff 2")
  , ("odd_riff_3", "Odd riff 3")
  , ("outro", "Outro")
  , ("outro_a", "Outro a")
  , ("outro_b", "Outro b")
  , ("ending", "Ending")
  , ("end_wankery", "End wankery")
  , ("big_end_1", "Big ending 1")
  , ("big_end_2", "Big ending 2")
  ]
