{-# LANGUAGE OverloadedStrings #-}
module Onyx.Sections.RB3
( findRBN2Section
) where

import           Data.Char           (isAlphaNum)
import qualified Data.HashMap.Strict as HM
import qualified Data.Text           as T

rbn2LookupTable :: HM.HashMap T.Text (T.Text, T.Text)
rbn2LookupTable = let

  rbn2Sections :: [(T.Text, T.Text)]
  rbn2Sections =
    [ ("intro", "Intro")
    , ("intro_a", "Intro A")
    , ("intro_b", "Intro B")
    , ("intro_c", "Intro C")
    , ("intro_d", "Intro D")
    , ("intro_e", "Intro E")
    , ("intro_slow", "Intro Slow")
    , ("intro_slow_a", "Intro Slow A")
    , ("intro_slow_b", "Intro Slow B")
    , ("intro_slow_c", "Intro Slow C")
    , ("intro_slow_d", "Intro Slow D")
    , ("intro_slow_1", "Intro Slow 1")
    , ("intro_fast", "Intro Fast")
    , ("intro_fast_a", "Intro Fast A")
    , ("intro_fast_b", "Intro Fast B")
    , ("intro_fast_c", "Intro Fast C")
    , ("intro_fast_d", "Intro Fast D")
    , ("intro_heavy", "Intro Heavy")
    , ("intro_heavy_a", "Intro Heavy A")
    , ("intro_heavy_b", "Intro Heavy B")
    , ("intro_heavy_c", "Intro Heavy C")
    , ("intro_heavy_d", "Intro Heavy D")
    , ("quiet_intro", "Quiet Intro")
    , ("quiet_intro_a", "Quiet Intro A")
    , ("quiet_intro_b", "Quiet Intro B")
    , ("quiet_intro_c", "Quiet Intro C")
    , ("quiet_intro_d", "Quiet Intro D")
    , ("noise_intro", "Noise Intro")
    , ("noise_intro_a", "Noise Intro A")
    , ("noise_intro_b", "Noise Intro B")
    , ("noise_intro_c", "Noise Intro C")
    , ("noise_intro_d", "Noise Intro D")
    , ("drum_intro", "Drum Intro")
    , ("drum_intro_a", "Drum Intro A")
    , ("drum_intro_b", "Drum Intro B")
    , ("drum_intro_c", "Drum Intro C")
    , ("drum_intro_d", "Drum Intro D")
    , ("bass_intro", "Bass Intro")
    , ("bass_intro_a", "Bass Intro A")
    , ("bass_intro_b", "Bass Intro B")
    , ("bass_intro_c", "Bass Intro C")
    , ("bass_intro_d", "Bass Intro D")
    , ("vocal_intro", "Vocal Intro")
    , ("vocal_intro_a", "Vocal Intro A")
    , ("vocal_intro_b", "Vocal Intro B")
    , ("vocal_intro_c", "Vocal Intro C")
    , ("vocal_intro_d", "Vocal Intro D")
    , ("gtr_intro", "Gtr Intro")
    , ("gtr_intro_a", "Gtr Intro A")
    , ("gtr_intro_b", "Gtr Intro B")
    , ("gtr_intro_c", "Gtr Intro C")
    , ("gtr_intro_d", "Gtr Intro D")
    , ("gtr_intro_e", "Gtr Intro E")
    , ("violin_intro", "Violin Intro")
    , ("violin_intro_a", "Violin Intro A")
    , ("violin_intro_b", "Violin Intro B")
    , ("violin_intro_c", "Violin Intro C")
    , ("violin_intro_d", "Violin Intro D")
    , ("strings_intro", "Strings Intro")
    , ("strings_intro_a", "Strings Intro A")
    , ("strings_intro_b", "Strings Intro B")
    , ("strings_intro_c", "Strings Intro C")
    , ("strings_intro_d", "Strings Intro D")
    , ("orch_intro", "Orch Intro")
    , ("orch_intro_a", "Orch Intro A")
    , ("orch_intro_b", "Orch Intro B")
    , ("orch_intro_c", "Orch Intro C")
    , ("orch_intro_d", "Orch Intro D")
    , ("horn_intro", "Horn Intro")
    , ("horn_intro_a", "Horn Intro A")
    , ("horn_intro_b", "Horn Intro B")
    , ("horn_intro_c", "Horn Intro C")
    , ("horn_intro_d", "Horn Intro D")
    , ("harmonica_intro", "Harmonica Intro")
    , ("harmonica_intro_a", "Harmonica Intro A")
    , ("harmonica_intro_b", "Harmonica Intro B")
    , ("harmonica_intro_c", "Harmonica Intro C")
    , ("harmonica_intro_d", "Harmonica Intro D")
    , ("organ_intro", "Organ Intro")
    , ("organ_intro_a", "Organ Intro A")
    , ("organ_intro_b", "Organ Intro B")
    , ("organ_intro_c", "Organ Intro C")
    , ("organ_intro_d", "Organ Intro D")
    , ("piano_intro", "Piano Intro")
    , ("piano_intro_a", "Piano Intro A")
    , ("piano_intro_b", "Piano Intro B")
    , ("piano_intro_c", "Piano Intro C")
    , ("piano_intro_d", "Piano Intro D")
    , ("keyboard_intro", "Keyboard Intro")
    , ("keyboard_intro_a", "Keyboard Intro A")
    , ("keyboard_intro_b", "Keyboard Intro B")
    , ("keyboard_intro_c", "Keyboard Intro C")
    , ("keyboard_intro_d", "Keyboard Intro D")
    , ("dj_intro", "DJ Intro")
    , ("dj_intro_a", "DJ Intro A")
    , ("dj_intro_b", "DJ Intro B")
    , ("dj_intro_c", "DJ Intro C")
    , ("dj_intro_d", "DJ Intro D")
    , ("intro_hook", "Intro Hook")
    , ("intro_hook_a", "Intro Hook A")
    , ("intro_hook_b", "Intro Hook B")
    , ("intro_hook_c", "Intro Hook C")
    , ("intro_hook_d", "Intro Hook D")
    , ("intro_riff", "Intro Riff")
    , ("intro_riff_a", "Intro Riff A")
    , ("intro_riff_b", "Intro Riff B")
    , ("intro_riff_c", "Intro Riff C")
    , ("intro_riff_d", "Intro Riff D")
    , ("fade_in", "Fade In")
    , ("fade_in_a", "Fade In A")
    , ("fade_in_b", "Fade In B")
    , ("fade_in_c", "Fade In C")
    , ("fade_in_d", "Fade In D")
    , ("drums_enter", "Drums Enter")
    , ("bass_enters", "Bass Enters")
    , ("gtr_enters", "Gtr Enters")
    , ("rhy_enters", "Gtr2 Enters")
    , ("band_enters", "Band Enters")
    , ("syth_enters", "Synth Enters") -- is this typo correct?
    , ("keyb_enters", "Keyboard Enters")
    , ("organ_enters", "Organ Enters")
    , ("piano_enters", "Piano Enters")
    , ("kick_it", "Kick It!")
    , ("intro_verse", "Intro Verse")
    , ("intro_verse_a", "Intro Verse A")
    , ("intro_verse_b", "Intro Verse B")
    , ("intro_verse_c", "Intro Verse C")
    , ("intro_verse_d", "Intro Verse D")
    , ("intro_chorus", "Intro Chorus")
    , ("intro_chorus_a", "Intro Chorus A")
    , ("intro_chorus_b", "Intro Chorus B")
    , ("intro_chorus_c", "Intro Chorus C")
    , ("intro_chorus_d", "Intro Chorus D")
    , ("verse", "Verse")
    , ("verse_a", "Verse A")
    , ("verse_b", "Verse B")
    , ("verse_c", "Verse C")
    , ("verse_d", "Verse D")
    , ("verse_e", "Verse E")
    , ("verse_f", "Verse F")
    , ("verse_1", "Verse 1")
    , ("verse_1a", "Verse 1A")
    , ("verse_1b", "Verse 1B")
    , ("verse_1c", "Verse 1C")
    , ("verse_1d", "Verse 1D")
    , ("verse_1e", "Verse 1E")
    , ("verse_1f", "Verse 1F")
    , ("verse_2", "Verse 2")
    , ("verse_2a", "Verse 2A")
    , ("verse_2b", "Verse 2B")
    , ("verse_2c", "Verse 2C")
    , ("verse_2d", "Verse 2D")
    , ("verse_2e", "Verse 2E")
    , ("verse_2f", "Verse 2F")
    , ("verse_3", "Verse 3")
    , ("verse_3a", "Verse 3A")
    , ("verse_3b", "Verse 3B")
    , ("verse_3c", "Verse 3C")
    , ("verse_3d", "Verse 3D")
    , ("verse_3e", "Verse 3E")
    , ("verse_3f", "Verse 3F")
    , ("verse_4", "Verse 4")
    , ("verse_4a", "Verse 4A")
    , ("verse_4b", "Verse 4B")
    , ("verse_4c", "Verse 4C")
    , ("verse_4d", "Verse 4D")
    , ("verse_5", "Verse 5")
    , ("verse_5a", "Verse 5A")
    , ("verse_5b", "Verse 5B")
    , ("verse_5c", "Verse 5C")
    , ("verse_5d", "Verse 5D")
    , ("verse_6", "Verse 6")
    , ("verse_6a", "Verse 6A")
    , ("verse_6b", "Verse 6B")
    , ("verse_6c", "Verse 6C")
    , ("verse_6d", "Verse 6D")
    , ("verse_7", "Verse 7")
    , ("verse_7a", "Verse 7A")
    , ("verse_7b", "Verse 7B")
    , ("verse_7c", "Verse 7C")
    , ("verse_7d", "Verse 7D")
    , ("verse_8", "Verse 8")
    , ("verse_8a", "Verse 8A")
    , ("verse_8b", "Verse 8B")
    , ("verse_8c", "Verse 8C")
    , ("verse_8d", "Verse 8D")
    , ("verse_9", "Verse 9")
    , ("verse_9a", "Verse 9A")
    , ("verse_9b", "Verse 9B")
    , ("verse_9c", "Verse 9C")
    , ("verse_9d", "Verse 9D")
    , ("alt_verse", "Alt Verse")
    , ("alt_verse_a", "Alt Verse A")
    , ("alt_verse_b", "Alt Verse B")
    , ("alt_verse_c", "Alt Verse C")
    , ("alt_verse_d", "Alt Verse D")
    , ("quiet_verse", "Quiet Verse")
    , ("quiet_verse_a", "Quiet Verse A")
    , ("quiet_verse_b", "Quiet Verse B")
    , ("quiet_verse_c", "Quiet Verse C")
    , ("quiet_verse_d", "Quiet Verse D")
    , ("preverse", "Pre-Verse")
    , ("preverse_a", "Pre-Verse A")
    , ("preverse_b", "Pre-Verse B")
    , ("preverse_c", "Pre-Verse C")
    , ("preverse_d", "Pre-Verse D")
    , ("preverse_1", "Pre-Verse 1")
    , ("preverse_1a", "Pre-Verse 1A")
    , ("preverse_1b", "Pre-Verse 1B")
    , ("preverse_1c", "Pre-Verse 1C")
    , ("preverse_1d", "Pre-Verse 1D")
    , ("preverse_2", "Pre-Verse 2")
    , ("preverse_2a", "Pre-Verse 2A")
    , ("preverse_2b", "Pre-Verse 2B")
    , ("preverse_2c", "Pre-Verse 2C")
    , ("preverse_2d", "Pre-Verse 2D")
    , ("preverse_3", "Pre-Verse 3")
    , ("preverse_3a", "Pre-Verse 3A")
    , ("preverse_3b", "Pre-Verse 3B")
    , ("preverse_3c", "Pre-Verse 3C")
    , ("preverse_3d", "Pre-Verse 3D")
    , ("preverse_4", "Pre-Verse 4")
    , ("preverse_4a", "Pre-Verse 4A")
    , ("preverse_4b", "Pre-Verse 4B")
    , ("preverse_4c", "Pre-Verse 4C")
    , ("preverse_4d", "Pre-Verse 4D")
    , ("preverse_5", "Pre-Verse 5")
    , ("preverse_5a", "Pre-Verse 5A")
    , ("preverse_5b", "Pre-Verse 5B")
    , ("preverse_5c", "Pre-Verse 5C")
    , ("preverse_5d", "Pre-Verse 5D")
    , ("postverse", "Post-Verse")
    , ("postverse_a", "Post-Verse A")
    , ("postverse_b", "Post-Verse B")
    , ("postverse_c", "Post-Verse C")
    , ("postverse_d", "Post-Verse D")
    , ("postverse_1", "Post-Verse 1")
    , ("postverse_1a", "Post-Verse 1A")
    , ("postverse_1b", "Post-Verse 1B")
    , ("postverse_1c", "Post-Verse 1C")
    , ("postverse_1d", "Post-Verse 1D")
    , ("postverse_2", "Post-Verse 2")
    , ("postverse_2a", "Post-Verse 2A")
    , ("postverse_2b", "Post-Verse 2B")
    , ("postverse_2c", "Post-Verse 2C")
    , ("postverse_2d", "Post-Verse 2D")
    , ("postverse_3", "Post-Verse 3")
    , ("postverse_3a", "Post-Verse 3A")
    , ("postverse_3b", "Post-Verse 3B")
    , ("postverse_3c", "Post-Verse 3C")
    , ("postverse_3d", "Post-Verse 3D")
    , ("postverse_4", "Post-Verse 4")
    , ("postverse_4a", "Post-Verse 4A")
    , ("postverse_4b", "Post-Verse 4B")
    , ("postverse_4c", "Post-Verse 4C")
    , ("postverse_4d", "Post-Verse 4D")
    , ("postverse_5", "Post-Verse 5")
    , ("postverse_5a", "Post-Verse 5A")
    , ("postverse_5b", "Post-Verse 5B")
    , ("postverse_5c", "Post-Verse 5C")
    , ("postverse_5d", "Post-Verse 5D")
    , ("chorus", "Chorus")
    , ("chorus_a", "Chorus A")
    , ("chorus_b", "Chorus B")
    , ("chorus_c", "Chorus C")
    , ("chorus_d", "Chorus D")
    , ("chorus_1", "Chorus 1")
    , ("chorus_1a", "Chorus 1A")
    , ("chorus_1b", "Chorus 1B")
    , ("chorus_1c", "Chorus 1C")
    , ("chorus_1d", "Chorus 1D")
    , ("chorus_2", "Chorus 2")
    , ("chorus_2a", "Chorus 2A")
    , ("chorus_2b", "Chorus 2B")
    , ("chorus_2c", "Chorus 2C")
    , ("chorus_2d", "Chorus 2D")
    , ("chorus_3", "Chorus 3")
    , ("chorus_3a", "Chorus 3A")
    , ("chorus_3b", "Chorus 3B")
    , ("chorus_3c", "Chorus 3C")
    , ("chorus_3d", "Chorus 3D")
    , ("chorus_4", "Chorus 4")
    , ("chorus_4a", "Chorus 4A")
    , ("chorus_4b", "Chorus 4B")
    , ("chorus_4c", "Chorus 4C")
    , ("chorus_4d", "Chorus 4D")
    , ("chorus_5", "Chorus 5")
    , ("chorus_5a", "Chorus 5A")
    , ("chorus_5b", "Chorus 5B")
    , ("chorus_5c", "Chorus 5C")
    , ("chorus_5d", "Chorus 5D")
    , ("chorus_6", "Chorus 6")
    , ("chorus_6a", "Chorus 6A")
    , ("chorus_6b", "Chorus 6B")
    , ("chorus_6c", "Chorus 6C")
    , ("chorus_6d", "Chorus 6D")
    , ("chorus_7", "Chorus 7")
    , ("chorus_7a", "Chorus 7A")
    , ("chorus_7b", "Chorus 7B")
    , ("chorus_7c", "Chorus 7C")
    , ("chorus_7d", "Chorus 7D")
    , ("chorus_8", "Chorus 8")
    , ("chorus_8a", "Chorus 8A")
    , ("chorus_8b", "Chorus 8B")
    , ("chorus_8c", "Chorus 8C")
    , ("chorus_8d", "Chorus 8D")
    , ("chorus_9", "Chorus 9")
    , ("chorus_9a", "Chorus 9A")
    , ("chorus_9b", "Chorus 9B")
    , ("chorus_9c", "Chorus 9C")
    , ("chorus_9d", "Chorus 9D")
    , ("chorus_break", "Chorus Break")
    , ("chorus_break_a", "Chorus Break A")
    , ("chorus_break_b", "Chorus Break B")
    , ("chorus_break_c", "Chorus Break C")
    , ("chorus_break_d", "Chorus Break D")
    , ("breakdown_chorus", "Breakdown Chorus")
    , ("breakdown_chorus_a", "Breakdown Chorus A")
    , ("breakdown_chorus_b", "Breakdown Chorus B")
    , ("breakdown_chorus_c", "Breakdown Chorus C")
    , ("breakdown_chorus_d", "Breakdown Chorus D")
    , ("alt_chorus", "Alt Chorus")
    , ("alt_chorus_a", "Alt Chorus A")
    , ("alt_chorus_b", "Alt Chorus B")
    , ("alt_chorus_c", "Alt Chorus C")
    , ("alt_chorus_d", "Alt Chorus D")
    , ("prechorus", "Pre-Chorus")
    , ("prechorus_a", "Pre-Chorus A")
    , ("prechorus_b", "Pre-Chorus B")
    , ("prechorus_c", "Pre-Chorus C")
    , ("prechorus_d", "Pre-Chorus D")
    , ("prechorus_1", "Pre-Chorus 1")
    , ("prechorus_1a", "Pre-Chorus 1A")
    , ("prechorus_1b", "Pre-Chorus 1B")
    , ("prechorus_1c", "Pre-Chorus 1C")
    , ("prechorus_1d", "Pre-Chorus 1D")
    , ("prechorus_2", "Pre-Chorus 2")
    , ("prechorus_2a", "Pre-Chorus 2A")
    , ("prechorus_2b", "Pre-Chorus 2B")
    , ("prechorus_2c", "Pre-Chorus 2C")
    , ("prechorus_2d", "Pre-Chorus 2D")
    , ("prechorus_3", "Pre-Chorus 3")
    , ("prechorus_3a", "Pre-Chorus 3A")
    , ("prechorus_3b", "Pre-Chorus 3B")
    , ("prechorus_3c", "Pre-Chorus 3C")
    , ("prechorus_3d", "Pre-Chorus 3D")
    , ("prechorus_4", "Pre-Chorus 4")
    , ("prechorus_4a", "Pre-Chorus 4A")
    , ("prechorus_4b", "Pre-Chorus 4B")
    , ("prechorus_4c", "Pre-Chorus 4C")
    , ("prechorus_4d", "Pre-Chorus 4D")
    , ("prechorus_5", "Pre-Chorus 5")
    , ("prechorus_5a", "Pre-Chorus 5A")
    , ("prechorus_5b", "Pre-Chorus 5B")
    , ("prechorus_5c", "Pre-Chorus 5C")
    , ("prechorus_5d", "Pre-Chorus 5D")
    , ("postchorus", "Post-Chorus")
    , ("postchorus_a", "Post-Chorus A")
    , ("postchorus_b", "Post-Chorus B")
    , ("postchorus_c", "Post-Chorus C")
    , ("postchorus_d", "Post-Chorus D")
    , ("postchorus_1", "Post-Chorus 1")
    , ("postchorus_1a", "Post-Chorus 1A")
    , ("postchorus_1b", "Post-Chorus 1B")
    , ("postchorus_1c", "Post-Chorus 1C")
    , ("postchorus_1d", "Post-Chorus 1D")
    , ("postchorus_2", "Post-Chorus 2")
    , ("postchorus_2a", "Post-Chorus 2A")
    , ("postchorus_2b", "Post-Chorus 2B")
    , ("postchorus_2c", "Post-Chorus 2C")
    , ("postchorus_2d", "Post-Chorus 2D")
    , ("postchorus_3", "Post-Chorus 3")
    , ("postchorus_3a", "Post-Chorus 3A")
    , ("postchorus_3b", "Post-Chorus 3B")
    , ("postchorus_3c", "Post-Chorus 3C")
    , ("postchorus_3d", "Post-Chorus 3D")
    , ("postchorus_4", "Post-Chorus 4")
    , ("postchorus_4a", "Post-Chorus 4A")
    , ("postchorus_4b", "Post-Chorus 4B")
    , ("postchorus_4c", "Post-Chorus 4C")
    , ("postchorus_4d", "Post-Chorus 4D")
    , ("postchorus_5", "Post-Chorus 5")
    , ("postchorus_5a", "Post-Chorus 5A")
    , ("postchorus_5b", "Post-Chorus 5B")
    , ("postchorus_5c", "Post-Chorus 5C")
    , ("postchorus_5d", "Post-Chorus 5D")
    , ("bridge", "Bridge")
    , ("bridge_a", "Bridge A")
    , ("bridge_b", "Bridge B")
    , ("bridge_c", "Bridge C")
    , ("bridge_d", "Bridge D")
    , ("bridge_1", "Bridge 1")
    , ("bridge_1a", "Bridge 1A")
    , ("bridge_1b", "Bridge 1B")
    , ("bridge_1c", "Bridge 1C")
    , ("bridge_1d", "Bridge 1D")
    , ("bridge_2", "Bridge 2")
    , ("bridge_2a", "Bridge 2A")
    , ("bridge_2b", "Bridge 2B")
    , ("bridge_2c", "Bridge 2C")
    , ("bridge_2d", "Bridge 2D")
    , ("bridge_3", "Bridge 3")
    , ("bridge_3a", "Bridge 3A")
    , ("bridge_3b", "Bridge 3B")
    , ("bridge_3c", "Bridge 3C")
    , ("bridge_3d", "Bridge 3D")
    , ("bridge_4", "Bridge 4")
    , ("bridge_4a", "Bridge 4A")
    , ("bridge_4b", "Bridge 4B")
    , ("bridge_4c", "Bridge 4C")
    , ("bridge_4d", "Bridge 4D")
    , ("bridge_5", "Bridge 5")
    , ("bridge_5a", "Bridge 5A")
    , ("bridge_5b", "Bridge 5B")
    , ("bridge_5c", "Bridge 5C")
    , ("bridge_5d", "Bridge 5D")
    , ("bridge_6", "Bridge 6")
    , ("bridge_6a", "Bridge 6A")
    , ("bridge_6b", "Bridge 6B")
    , ("bridge_6c", "Bridge 6C")
    , ("bridge_6d", "Bridge 6D")
    , ("bridge_7", "Bridge 7")
    , ("bridge_7a", "Bridge 7A")
    , ("bridge_7b", "Bridge 7B")
    , ("bridge_7c", "Bridge 7C")
    , ("bridge_7d", "Bridge 7D")
    , ("bridge_8", "Bridge 8")
    , ("bridge_8a", "Bridge 8A")
    , ("bridge_8b", "Bridge 8B")
    , ("bridge_8c", "Bridge 8C")
    , ("bridge_8d", "Bridge 8D")
    , ("bridge_9", "Bridge 9")
    , ("bridge_9a", "Bridge 9A")
    , ("bridge_9b", "Bridge 9B")
    , ("bridge_9c", "Bridge 9C")
    , ("bridge_9d", "Bridge 9D")
    , ("gtr_solo", "Gtr Solo")
    , ("gtr_solo_a", "Gtr Solo A")
    , ("gtr_solo_b", "Gtr Solo B")
    , ("gtr_solo_c", "Gtr Solo C")
    , ("gtr_solo_d", "Gtr Solo D")
    , ("gtr_solo_e", "Gtr Solo E")
    , ("gtr_solo_f", "Gtr Solo F")
    , ("gtr_solo_g", "Gtr Solo G")
    , ("gtr_solo_h", "Gtr Solo H")
    , ("gtr_solo_i", "Gtr Solo I")
    , ("gtr_solo_j", "Gtr Solo J")
    , ("gtr_solo_k", "Gtr Solo K")
    , ("gtr_solo_l", "Gtr Solo L")
    , ("gtr_solo_m", "Gtr Solo M")
    , ("gtr_solo_n", "Gtr Solo N")
    , ("gtr_solo_o", "Gtr Solo O")
    , ("gtr_solo_p", "Gtr Solo P")
    , ("gtr_solo_q", "Gtr Solo Q")
    , ("gtr_solo_r", "Gtr Solo R")
    , ("gtr_solo_s", "Gtr Solo S")
    , ("gtr_solo_1", "Gtr Solo 1")
    , ("gtr_solo_1a", "Gtr Solo 1A")
    , ("gtr_solo_1b", "Gtr Solo 1B")
    , ("gtr_solo_1c", "Gtr Solo 1C")
    , ("gtr_solo_1d", "Gtr Solo 1D")
    , ("gtr_solo_1e", "Gtr Solo 1E")
    , ("gtr_solo_1f", "Gtr Solo 1F")
    , ("gtr_solo_1g", "Gtr Solo 1G")
    , ("gtr_solo_1h", "Gtr Solo 1H")
    , ("gtr_solo_1i", "Gtr Solo 1I")
    , ("gtr_solo_1j", "Gtr Solo 1J")
    , ("gtr_solo_1k", "Gtr Solo 1K")
    , ("gtr_solo_1l", "Gtr Solo 1L")
    , ("gtr_solo_1m", "Gtr Solo 1M")
    , ("gtr_solo_1n", "Gtr Solo 1N")
    , ("gtr_solo_2", "Gtr Solo 2")
    , ("gtr_solo_2a", "Gtr Solo 2A")
    , ("gtr_solo_2b", "Gtr Solo 2B")
    , ("gtr_solo_2c", "Gtr Solo 2C")
    , ("gtr_solo_2d", "Gtr Solo 2D")
    , ("gtr_solo_2e", "Gtr Solo 2E")
    , ("gtr_solo_2f", "Gtr Solo 2F")
    , ("gtr_solo_2g", "Gtr Solo 2G")
    , ("gtr_solo_2h", "Gtr Solo 2H")
    , ("gtr_solo_2i", "Gtr Solo 2I")
    , ("gtr_solo_2j", "Gtr Solo 2J")
    , ("gtr_solo_2k", "Gtr Solo 2K")
    , ("gtr_solo_2l", "Gtr Solo 2L")
    , ("gtr_solo_2m", "Gtr Solo 2M")
    , ("gtr_solo_2n", "Gtr Solo 2N")
    , ("gtr_solo_3", "Gtr Solo 3")
    , ("gtr_solo_3a", "Gtr Solo 3A")
    , ("gtr_solo_3b", "Gtr Solo 3B")
    , ("gtr_solo_3c", "Gtr Solo 3C")
    , ("gtr_solo_3d", "Gtr Solo 3D")
    , ("gtr_solo_3e", "Gtr Solo 3E")
    , ("gtr_solo_3f", "Gtr Solo 3F")
    , ("gtr_solo_3g", "Gtr Solo 3G")
    , ("gtr_solo_3h", "Gtr Solo 3H")
    , ("gtr_solo_3i", "Gtr Solo 3I")
    , ("gtr_solo_3j", "Gtr Solo 3J")
    , ("gtr_solo_3k", "Gtr Solo 3K")
    , ("gtr_solo_3l", "Gtr Solo 3L")
    , ("gtr_solo_3m", "Gtr Solo 3M")
    , ("gtr_solo_3n", "Gtr Solo 3N")
    , ("gtr_solo_4", "Gtr Solo 4")
    , ("gtr_solo_4a", "Gtr Solo 4A")
    , ("gtr_solo_4b", "Gtr Solo 4B")
    , ("gtr_solo_4c", "Gtr Solo 4C")
    , ("gtr_solo_4d", "Gtr Solo 4D")
    , ("gtr_solo_4e", "Gtr Solo 4E")
    , ("gtr_solo_4f", "Gtr Solo 4F")
    , ("gtr_solo_4g", "Gtr Solo 4G")
    , ("gtr_solo_4h", "Gtr Solo 4H")
    , ("gtr_solo_4i", "Gtr Solo 4I")
    , ("gtr_solo_4j", "Gtr Solo 4J")
    , ("gtr_solo_4k", "Gtr Solo 4K")
    , ("gtr_solo_4l", "Gtr Solo 4L")
    , ("gtr_solo_4m", "Gtr Solo 4M")
    , ("gtr_solo_4n", "Gtr Solo 4N")
    , ("gtr_solo_5", "Gtr Solo 5")
    , ("gtr_solo_5a", "Gtr Solo 5A")
    , ("gtr_solo_5b", "Gtr Solo 5B")
    , ("gtr_solo_5c", "Gtr Solo 5C")
    , ("gtr_solo_5d", "Gtr Solo 5D")
    , ("gtr_solo_5e", "Gtr Solo 5E")
    , ("gtr_solo_5f", "Gtr Solo 5F")
    , ("gtr_solo_5g", "Gtr Solo 5G")
    , ("gtr_solo_5h", "Gtr Solo 5H")
    , ("gtr_solo_5i", "Gtr Solo 5I")
    , ("gtr_solo_5j", "Gtr Solo 5J")
    , ("gtr_solo_5k", "Gtr Solo 5K")
    , ("gtr_solo_5l", "Gtr Solo 5L")
    , ("gtr_solo_5m", "Gtr Solo 5M")
    , ("gtr_solo_5n", "Gtr Solo 5N")
    , ("gtr_solo_6", "Gtr Solo 6")
    , ("gtr_solo_6a", "Gtr Solo 6A")
    , ("gtr_solo_6b", "Gtr Solo 6B")
    , ("gtr_solo_6c", "Gtr Solo 6C")
    , ("gtr_solo_6d", "Gtr Solo 6D")
    , ("gtr_solo_6e", "Gtr Solo 6E")
    , ("gtr_solo_6f", "Gtr Solo 6F")
    , ("gtr_solo_6g", "Gtr Solo 6G")
    , ("gtr_solo_6h", "Gtr Solo 6H")
    , ("gtr_solo_6i", "Gtr Solo 6I")
    , ("gtr_solo_6j", "Gtr Solo 6J")
    , ("gtr_solo_6k", "Gtr Solo 6K")
    , ("gtr_solo_6l", "Gtr Solo 6L")
    , ("gtr_solo_6m", "Gtr Solo 6M")
    , ("gtr_solo_6n", "Gtr Solo 6N")
    , ("gtr_solo_7", "Gtr Solo 7")
    , ("gtr_solo_7a", "Gtr Solo 7A")
    , ("gtr_solo_7b", "Gtr Solo 7B")
    , ("gtr_solo_7c", "Gtr Solo 7C")
    , ("gtr_solo_7d", "Gtr Solo 7D")
    , ("gtr_solo_7e", "Gtr Solo 7E")
    , ("gtr_solo_7f", "Gtr Solo 7F")
    , ("gtr_solo_7g", "Gtr Solo 7G")
    , ("gtr_solo_7h", "Gtr Solo 7H")
    , ("gtr_solo_7i", "Gtr Solo 7I")
    , ("gtr_solo_7j", "Gtr Solo 7J")
    , ("gtr_solo_7k", "Gtr Solo 7K")
    , ("gtr_solo_7l", "Gtr Solo 7L")
    , ("gtr_solo_7m", "Gtr Solo 7M")
    , ("gtr_solo_7n", "Gtr Solo 7N")
    , ("gtr_solo_8", "Gtr Solo 8")
    , ("gtr_solo_8a", "Gtr Solo 8A")
    , ("gtr_solo_8b", "Gtr Solo 8B")
    , ("gtr_solo_8c", "Gtr Solo 8C")
    , ("gtr_solo_8d", "Gtr Solo 8D")
    , ("gtr_solo_8e", "Gtr Solo 8E")
    , ("gtr_solo_8f", "Gtr Solo 8F")
    , ("gtr_solo_8g", "Gtr Solo 8G")
    , ("gtr_solo_8h", "Gtr Solo 8H")
    , ("gtr_solo_8i", "Gtr Solo 8I")
    , ("gtr_solo_8j", "Gtr Solo 8J")
    , ("gtr_solo_8k", "Gtr Solo 8K")
    , ("gtr_solo_8l", "Gtr Solo 8L")
    , ("gtr_solo_8m", "Gtr Solo 8M")
    , ("gtr_solo_8n", "Gtr Solo 8N")
    , ("gtr_solo_9", "Gtr Solo 9")
    , ("gtr_solo_9a", "Gtr Solo 9A")
    , ("gtr_solo_9b", "Gtr Solo 9B")
    , ("gtr_solo_9c", "Gtr Solo 9C")
    , ("gtr_solo_9d", "Gtr Solo 9D")
    , ("gtr_solo_9e", "Gtr Solo 9E")
    , ("gtr_solo_9f", "Gtr Solo 9F")
    , ("gtr_solo_9g", "Gtr Solo 9G")
    , ("gtr_solo_9h", "Gtr Solo 9H")
    , ("gtr_solo_9i", "Gtr Solo 9I")
    , ("gtr_solo_9j", "Gtr Solo 9J")
    , ("gtr_solo_9k", "Gtr Solo 9K")
    , ("gtr_solo_9l", "Gtr Solo 9L")
    , ("gtr_solo_9m", "Gtr Solo 9M")
    , ("gtr_solo_9n", "Gtr Solo 9N")
    , ("slide_solo", "Slide Solo")
    , ("slide_solo_a", "Slide Solo A")
    , ("slide_solo_b", "Slide Solo B")
    , ("slide_solo_c", "Slide Solo C")
    , ("slide_solo_d", "Slide Solo D")
    , ("slide_solo_1", "Slide Solo 1")
    , ("slide_solo_1a", "Slide Solo 1A")
    , ("slide_solo_1b", "Slide Solo 1B")
    , ("slide_solo_1c", "Slide Solo 1C")
    , ("slide_solo_1d", "Slide Solo 1D")
    , ("slide_solo_2", "Slide Solo 2")
    , ("slide_solo_2a", "Slide Solo 2A")
    , ("slide_solo_2b", "Slide Solo 2B")
    , ("slide_solo_2c", "Slide Solo 2C")
    , ("slide_solo_2d", "Slide Solo 2D")
    , ("slide_solo_3", "Slide Solo 3")
    , ("slide_solo_3a", "Slide Solo 3A")
    , ("slide_solo_3b", "Slide Solo 3B")
    , ("slide_solo_3c", "Slide Solo 3C")
    , ("slide_solo_3d", "Slide Solo 3D")
    , ("slide_solo_4", "Slide Solo 4")
    , ("slide_solo_4a", "Slide Solo 4A")
    , ("slide_solo_4b", "Slide Solo 4B")
    , ("slide_solo_4c", "Slide Solo 4C")
    , ("slide_solo_4d", "Slide Solo 4D")
    , ("drum_solo", "Drum Solo")
    , ("drum_solo_a", "Drum Solo A")
    , ("drum_solo_b", "Drum Solo B")
    , ("drum_solo_c", "Drum Solo C")
    , ("drum_solo_d", "Drum Solo D")
    , ("drum_solo_1", "Drum Solo 1")
    , ("drum_solo_1a", "Drum Solo 1A")
    , ("drum_solo_1b", "Drum Solo 1B")
    , ("drum_solo_1c", "Drum Solo 1C")
    , ("drum_solo_1d", "Drum Solo 1D")
    , ("drum_solo_2", "Drum Solo 2")
    , ("drum_solo_2a", "Drum Solo 2A")
    , ("drum_solo_2b", "Drum Solo 2B")
    , ("drum_solo_2c", "Drum Solo 2C")
    , ("drum_solo_2d", "Drum Solo 2D")
    , ("drum_solo_3", "Drum Solo 3")
    , ("drum_solo_3a", "Drum Solo 3A")
    , ("drum_solo_3b", "Drum Solo 3B")
    , ("drum_solo_3c", "Drum Solo 3C")
    , ("drum_solo_3d", "Drum Solo 3D")
    , ("drum_solo_4", "Drum Solo 4")
    , ("drum_solo_4a", "Drum Solo 4A")
    , ("drum_solo_4b", "Drum Solo 4B")
    , ("drum_solo_4c", "Drum Solo 4C")
    , ("drum_solo_4d", "Drum Solo 4D")
    , ("perc_solo", "Percussion Solo")
    , ("perc_solo_a", "Percussion Solo A")
    , ("perc_solo_b", "Percussion Solo B")
    , ("perc_solo_c", "Percussion Solo C")
    , ("perc_solo_d", "Percussion Solo D")
    , ("perc_solo_1", "Percussion Solo 1")
    , ("perc_solo_1a", "Percussion Solo 1A")
    , ("perc_solo_1b", "Percussion Solo 1B")
    , ("perc_solo_1c", "Percussion Solo 1C")
    , ("perc_solo_1d", "Percussion Solo 1D")
    , ("perc_solo_2", "Percussion Solo 2")
    , ("perc_solo_2a", "Percussion Solo 2A")
    , ("perc_solo_2b", "Percussion Solo 2B")
    , ("perc_solo_2c", "Percussion Solo 2C")
    , ("perc_solo_2d", "Percussion Solo 2D")
    , ("perc_solo_3", "Percussion Solo 3")
    , ("perc_solo_3a", "Percussion Solo 3A")
    , ("perc_solo_3b", "Percussion Solo 3B")
    , ("perc_solo_3c", "Percussion Solo 3C")
    , ("perc_solo_3d", "Percussion Solo 3D")
    , ("perc_solo_4", "Percussion Solo 4")
    , ("perc_solo_4a", "Percussion Solo 4A")
    , ("perc_solo_4b", "Percussion Solo 4B")
    , ("perc_solo_4c", "Percussion Solo 4C")
    , ("perc_solo_4d", "Percussion Solo 4D")
    , ("bass_solo", "Bass Solo")
    , ("bass_solo_a", "Bass Solo A")
    , ("bass_solo_b", "Bass Solo B")
    , ("bass_solo_c", "Bass Solo C")
    , ("bass_solo_d", "Bass Solo D")
    , ("bass_solo_1", "Bass Solo 1")
    , ("bass_solo_1a", "Bass Solo 1A")
    , ("bass_solo_1b", "Bass Solo 1B")
    , ("bass_solo_1c", "Bass Solo 1C")
    , ("bass_solo_1d", "Bass Solo 1D")
    , ("bass_solo_2", "Bass Solo 2")
    , ("bass_solo_2a", "Bass Solo 2A")
    , ("bass_solo_2b", "Bass Solo 2B")
    , ("bass_solo_2c", "Bass Solo 2C")
    , ("bass_solo_2d", "Bass Solo 2D")
    , ("bass_solo_3", "Bass Solo 3")
    , ("bass_solo_3a", "Bass Solo 3A")
    , ("bass_solo_3b", "Bass Solo 3B")
    , ("bass_solo_3c", "Bass Solo 3C")
    , ("bass_solo_3d", "Bass Solo 3D")
    , ("bass_solo_4", "Bass Solo 4")
    , ("bass_solo_4a", "Bass Solo 4A")
    , ("bass_solo_4b", "Bass Solo 4B")
    , ("bass_solo_4c", "Bass Solo 4C")
    , ("bass_solo_4d", "Bass Solo 4D")
    , ("organ_solo", "Organ Solo")
    , ("organ_solo_a", "Organ Solo A")
    , ("organ_solo_b", "Organ Solo B")
    , ("organ_solo_c", "Organ Solo C")
    , ("organ_solo_d", "Organ Solo D")
    , ("organ_solo_1", "Organ Solo 1")
    , ("organ_solo_1a", "Organ Solo 1A")
    , ("organ_solo_1b", "Organ Solo 1B")
    , ("organ_solo_1c", "Organ Solo 1C")
    , ("organ_solo_1d", "Organ Solo 1D")
    , ("organ_solo_2", "Organ Solo 2")
    , ("organ_solo_2a", "Organ Solo 2A")
    , ("organ_solo_2b", "Organ Solo 2B")
    , ("organ_solo_2c", "Organ Solo 2C")
    , ("organ_solo_2d", "Organ Solo 2D")
    , ("organ_solo_3", "Organ Solo 3")
    , ("organ_solo_3a", "Organ Solo 3A")
    , ("organ_solo_3b", "Organ Solo 3B")
    , ("organ_solo_3c", "Organ Solo 3C")
    , ("organ_solo_3d", "Organ Solo 3D")
    , ("organ_solo_4", "Organ Solo 4")
    , ("organ_solo_4a", "Organ Solo 4A")
    , ("organ_solo_4b", "Organ Solo 4B")
    , ("organ_solo_4c", "Organ Solo 4C")
    , ("organ_solo_4d", "Organ Solo 4D")
    , ("piano_solo", "Piano Solo")
    , ("piano_solo_a", "Piano Solo A")
    , ("piano_solo_b", "Piano Solo B")
    , ("piano_solo_c", "Piano Solo C")
    , ("piano_solo_d", "Piano Solo D")
    , ("piano_solo_1", "Piano Solo 1")
    , ("piano_solo_1a", "Piano Solo 1A")
    , ("piano_solo_1b", "Piano Solo 1B")
    , ("piano_solo_1c", "Piano Solo 1C")
    , ("piano_solo_1d", "Piano Solo 1D")
    , ("piano_solo_2", "Piano Solo 2")
    , ("piano_solo_2a", "Piano Solo 2A")
    , ("piano_solo_2b", "Piano Solo 2B")
    , ("piano_solo_2c", "Piano Solo 2C")
    , ("piano_solo_2d", "Piano Solo 2D")
    , ("piano_solo_3", "Piano Solo 3")
    , ("piano_solo_3a", "Piano Solo 3A")
    , ("piano_solo_3b", "Piano Solo 3B")
    , ("piano_solo_3c", "Piano Solo 3C")
    , ("piano_solo_3d", "Piano Solo 3D")
    , ("piano_solo_4", "Piano Solo 4")
    , ("piano_solo_4a", "Piano Solo 4A")
    , ("piano_solo_4b", "Piano Solo 4B")
    , ("piano_solo_4c", "Piano Solo 4C")
    , ("piano_solo_4d", "Piano Solo 4D")
    , ("keyboard_solo", "Keyboard Solo")
    , ("keyboard_solo_a", "Keyboard Solo A")
    , ("keyboard_solo_b", "Keyboard Solo B")
    , ("keyboard_solo_c", "Keyboard Solo C")
    , ("keyboard_solo_d", "Keyboard Solo D")
    , ("keyboard_solo_1", "Keyboard Solo 1")
    , ("keyboard_solo_1a", "Keyboard Solo 1A")
    , ("keyboard_solo_1b", "Keyboard Solo 1B")
    , ("keyboard_solo_1c", "Keyboard Solo 1C")
    , ("keyboard_solo_1d", "Keyboard Solo 1D")
    , ("keyboard_solo_2", "Keyboard Solo 2")
    , ("keyboard_solo_2a", "Keyboard Solo 2A")
    , ("keyboard_solo_2b", "Keyboard Solo 2B")
    , ("keyboard_solo_2c", "Keyboard Solo 2C")
    , ("keyboard_solo_2d", "Keyboard Solo 2D")
    , ("keyboard_solo_3", "Keyboard Solo 3")
    , ("keyboard_solo_3a", "Keyboard Solo 3A")
    , ("keyboard_solo_3b", "Keyboard Solo 3B")
    , ("keyboard_solo_3c", "Keyboard Solo 3C")
    , ("keyboard_solo_3d", "Keyboard Solo 3D")
    , ("keyboard_solo_4", "Keyboard Solo 4")
    , ("keyboard_solo_4a", "Keyboard Solo 4A")
    , ("keyboard_solo_4b", "Keyboard Solo 4B")
    , ("keyboard_solo_4c", "Keyboard Solo 4C")
    , ("keyboard_solo_4d", "Keyboard Solo 4D")
    , ("synth_solo", "Synth Solo")
    , ("synth_solo_a", "Synth Solo A")
    , ("synth_solo_b", "Synth Solo B")
    , ("synth_solo_c", "Synth Solo C")
    , ("synth_solo_d", "Synth Solo D")
    , ("synth_solo_1", "Synth Solo 1")
    , ("synth_solo_1a", "Synth Solo 1A")
    , ("synth_solo_1b", "Synth Solo 1B")
    , ("synth_solo_1c", "Synth Solo 1C")
    , ("synth_solo_1d", "Synth Solo 1D")
    , ("synth_solo_2", "Synth Solo 2")
    , ("synth_solo_2a", "Synth Solo 2A")
    , ("synth_solo_2b", "Synth Solo 2B")
    , ("synth_solo_2c", "Synth Solo 2C")
    , ("synth_solo_2d", "Synth Solo 2D")
    , ("synth_solo_3", "Synth Solo 3")
    , ("synth_solo_3a", "Synth Solo 3A")
    , ("synth_solo_3b", "Synth Solo 3B")
    , ("synth_solo_3c", "Synth Solo 3C")
    , ("synth_solo_3d", "Synth Solo 3D")
    , ("synth_solo_4", "Synth Solo 4")
    , ("synth_solo_4a", "Synth Solo 4A")
    , ("synth_solo_4b", "Synth Solo 4B")
    , ("synth_solo_4c", "Synth Solo 4C")
    , ("synth_solo_4d", "Synth Solo 4D")
    , ("harmonica_solo", "Harmonica Solo")
    , ("harmonica_solo_a", "Harmonica Solo A")
    , ("harmonica_solo_b", "Harmonica Solo B")
    , ("harmonica_solo_c", "Harmonica Solo C")
    , ("harmonica_solo_d", "Harmonica Solo D")
    , ("harmonica_solo_1", "Harmonica Solo 1")
    , ("harmonica_solo_1a", "Harmonica Solo 1A")
    , ("harmonica_solo_1b", "Harmonica Solo 1B")
    , ("harmonica_solo_1c", "Harmonica Solo 1C")
    , ("harmonica_solo_1d", "Harmonica Solo 1D")
    , ("harmonica_solo_2", "Harmonica Solo 2")
    , ("harmonica_solo_2a", "Harmonica Solo 2A")
    , ("harmonica_solo_2b", "Harmonica Solo 2B")
    , ("harmonica_solo_2c", "Harmonica Solo 2C")
    , ("harmonica_solo_2d", "Harmonica Solo 2D")
    , ("harmonica_solo_3", "Harmonica Solo 3")
    , ("harmonica_solo_3a", "Harmonica Solo 3A")
    , ("harmonica_solo_3b", "Harmonica Solo 3B")
    , ("harmonica_solo_3c", "Harmonica Solo 3C")
    , ("harmonica_solo_3d", "Harmonica Solo 3D")
    , ("harmonica_solo_4", "Harmonica Solo 4")
    , ("harmonica_solo_4a", "Harmonica Solo 4A")
    , ("harmonica_solo_4b", "Harmonica Solo 4B")
    , ("harmonica_solo_4c", "Harmonica Solo 4C")
    , ("harmonica_solo_4d", "Harmonica Solo 4D")
    , ("sax_solo", "Sax Solo")
    , ("sax_solo_a", "Sax Solo A")
    , ("sax_solo_b", "Sax Solo B")
    , ("sax_solo_c", "Sax Solo C")
    , ("sax_solo_d", "Sax Solo D")
    , ("sax_solo_1", "Sax Solo 1")
    , ("sax_solo_1a", "Sax Solo 1A")
    , ("sax_solo_1b", "Sax Solo 1B")
    , ("sax_solo_1c", "Sax Solo 1C")
    , ("sax_solo_1d", "Sax Solo 1D")
    , ("sax_solo_2", "Sax Solo 2")
    , ("sax_solo_2a", "Sax Solo 2A")
    , ("sax_solo_2b", "Sax Solo 2B")
    , ("sax_solo_2c", "Sax Solo 2C")
    , ("sax_solo_2d", "Sax Solo 2D")
    , ("sax_solo_3", "Sax Solo 3")
    , ("sax_solo_3a", "Sax Solo 3A")
    , ("sax_solo_3b", "Sax Solo 3B")
    , ("sax_solo_3c", "Sax Solo 3C")
    , ("sax_solo_3d", "Sax Solo 3D")
    , ("sax_solo_4", "Sax Solo 4")
    , ("sax_solo_4a", "Sax Solo 4A")
    , ("sax_solo_4b", "Sax Solo 4B")
    , ("sax_solo_4c", "Sax Solo 4C")
    , ("sax_solo_4d", "Sax Solo 4D")
    , ("horn_solo", "Horn Solo")
    , ("horn_solo_a", "Horn Solo A")
    , ("horn_solo_b", "Horn Solo B")
    , ("horn_solo_c", "Horn Solo C")
    , ("horn_solo_d", "Horn Solo D")
    , ("horn_solo_1", "Horn Solo 1")
    , ("horn_solo_1a", "Horn Solo 1A")
    , ("horn_solo_1b", "Horn Solo 1B")
    , ("horn_solo_1c", "Horn Solo 1C")
    , ("horn_solo_1d", "Horn Solo 1D")
    , ("horn_solo_2", "Horn Solo 2")
    , ("horn_solo_2a", "Horn Solo 2A")
    , ("horn_solo_2b", "Horn Solo 2B")
    , ("horn_solo_2c", "Horn Solo 2C")
    , ("horn_solo_2d", "Horn Solo 2D")
    , ("horn_solo_3", "Horn Solo 3")
    , ("horn_solo_3a", "Horn Solo 3A")
    , ("horn_solo_3b", "Horn Solo 3B")
    , ("horn_solo_3c", "Horn Solo 3C")
    , ("horn_solo_3d", "Horn Solo 3D")
    , ("horn_solo_4", "Horn Solo 4")
    , ("horn_solo_4a", "Horn Solo 4A")
    , ("horn_solo_4b", "Horn Solo 4B")
    , ("horn_solo_4c", "Horn Solo 4C")
    , ("horn_solo_4d", "Horn Solo 4D")
    , ("flute_solo", "Flute Solo")
    , ("flute_solo_a", "Flute Solo A")
    , ("flute_solo_b", "Flute Solo B")
    , ("flute_solo_c", "Flute Solo C")
    , ("flute_solo_d", "Flute Solo D")
    , ("flute_solo_1", "Flute Solo 1")
    , ("flute_solo_1a", "Flute Solo 1A")
    , ("flute_solo_1b", "Flute Solo 1B")
    , ("flute_solo_1c", "Flute Solo 1C")
    , ("flute_solo_1d", "Flute Solo 1D")
    , ("flute_solo_2", "Flute Solo 2")
    , ("flute_solo_2a", "Flute Solo 2A")
    , ("flute_solo_2b", "Flute Solo 2B")
    , ("flute_solo_2c", "Flute Solo 2C")
    , ("flute_solo_2d", "Flute Solo 2D")
    , ("flute_solo_3", "Flute Solo 3")
    , ("flute_solo_3a", "Flute Solo 3A")
    , ("flute_solo_3b", "Flute Solo 3B")
    , ("flute_solo_3c", "Flute Solo 3C")
    , ("flute_solo_3d", "Flute Solo 3D")
    , ("flute_solo_4", "Flute Solo 4")
    , ("flute_solo_4a", "Flute Solo 4A")
    , ("flute_solo_4b", "Flute Solo 4B")
    , ("flute_solo_4c", "Flute Solo 4C")
    , ("flute_solo_4d", "Flute Solo 4D")
    , ("noise_solo", "Noise Solo")
    , ("noise_solo_a", "Noise Solo A")
    , ("noise_solo_b", "Noise Solo B")
    , ("noise_solo_c", "Noise Solo C")
    , ("noise_solo_d", "Noise Solo D")
    , ("noise_solo_1", "Noise Solo 1")
    , ("noise_solo_1a", "Noise Solo 1A")
    , ("noise_solo_1b", "Noise Solo 1B")
    , ("noise_solo_1c", "Noise Solo 1C")
    , ("noise_solo_1d", "Noise Solo 1D")
    , ("noise_solo_2", "Noise Solo 2")
    , ("noise_solo_2a", "Noise Solo 2A")
    , ("noise_solo_2b", "Noise Solo 2B")
    , ("noise_solo_2c", "Noise Solo 2C")
    , ("noise_solo_2d", "Noise Solo 2D")
    , ("noise_solo_3", "Noise Solo 3")
    , ("noise_solo_3a", "Noise Solo 3A")
    , ("noise_solo_3b", "Noise Solo 3B")
    , ("noise_solo_3c", "Noise Solo 3C")
    , ("noise_solo_3d", "Noise Solo 3D")
    , ("noise_solo_4", "Noise Solo 4")
    , ("noise_solo_4a", "Noise Solo 4A")
    , ("noise_solo_4b", "Noise Solo 4B")
    , ("noise_solo_4c", "Noise Solo 4C")
    , ("noise_solo_4d", "Noise Solo 4D")
    , ("dj_solo", "DJ Solo")
    , ("dj_solo_a", "DJ Solo A")
    , ("dj_solo_b", "DJ Solo B")
    , ("dj_solo_c", "DJ Solo C")
    , ("dj_solo_d", "DJ Solo D")
    , ("dj_solo_1", "DJ Solo 1")
    , ("dj_solo_1a", "DJ Solo 1A")
    , ("dj_solo_1b", "DJ Solo 1B")
    , ("dj_solo_1c", "DJ Solo 1C")
    , ("dj_solo_1d", "DJ Solo 1D")
    , ("dj_solo_2", "DJ Solo 2")
    , ("dj_solo_2a", "DJ Solo 2A")
    , ("dj_solo_2b", "DJ Solo 2B")
    , ("dj_solo_2c", "DJ Solo 2C")
    , ("dj_solo_2d", "DJ Solo 2D")
    , ("dj_solo_3", "DJ Solo 3")
    , ("dj_solo_3a", "DJ Solo 3A")
    , ("dj_solo_3b", "DJ Solo 3B")
    , ("dj_solo_3c", "DJ Solo 3C")
    , ("dj_solo_3d", "DJ Solo 3D")
    , ("dj_solo_4", "DJ Solo 4")
    , ("dj_solo_4a", "DJ Solo 4A")
    , ("dj_solo_4b", "DJ Solo 4B")
    , ("dj_solo_4c", "DJ Solo 4C")
    , ("dj_solo_4d", "DJ Solo 4D")
    , ("slow_part", "Slow Part")
    , ("slow_part_a", "Slow Part A")
    , ("slow_part_b", "Slow Part B")
    , ("slow_part_c", "Slow Part C")
    , ("slow_part_d", "Slow Part D")
    , ("slow_part_1", "Slow Part 1")
    , ("slow_part_1a", "Slow Part 1A")
    , ("slow_part_1b", "Slow Part 1B")
    , ("slow_part_1c", "Slow Part 1C")
    , ("slow_part_1d", "Slow Part 1D")
    , ("slow_part_2", "Slow Part 2")
    , ("slow_part_2a", "Slow Part 2A")
    , ("slow_part_2b", "Slow Part 2B")
    , ("slow_part_2c", "Slow Part 2C")
    , ("slow_part_2d", "Slow Part 2D")
    , ("slow_part_3", "Slow Part 3")
    , ("slow_part_3a", "Slow Part 3A")
    , ("slow_part_3b", "Slow Part 3B")
    , ("slow_part_3c", "Slow Part 3C")
    , ("slow_part_3d", "Slow Part 3D")
    , ("slow_part_4", "Slow Part 4")
    , ("slow_part_4a", "Slow Part 4A")
    , ("slow_part_4b", "Slow Part 4B")
    , ("slow_part_4c", "Slow Part 4C")
    , ("slow_part_4d", "Slow Part 4D")
    , ("fast_part", "Fast Part")
    , ("fast_part_a", "Fast Part A")
    , ("fast_part_b", "Fast Part B")
    , ("fast_part_c", "Fast Part C")
    , ("fast_part_d", "Fast Part D")
    , ("fast_part_1", "Fast Part 1")
    , ("fast_part_1a", "Fast Part 1A")
    , ("fast_part_1b", "Fast Part 1B")
    , ("fast_part_1c", "Fast Part 1C")
    , ("fast_part_1d", "Fast Part 1D")
    , ("fast_part_2", "Fast Part 2")
    , ("fast_part_2a", "Fast Part 2A")
    , ("fast_part_2b", "Fast Part 2B")
    , ("fast_part_2c", "Fast Part 2C")
    , ("fast_part_2d", "Fast Part 2D")
    , ("fast_part_3", "Fast Part 3")
    , ("fast_part_3a", "Fast Part 3A")
    , ("fast_part_3b", "Fast Part 3B")
    , ("fast_part_3c", "Fast Part 3C")
    , ("fast_part_3d", "Fast Part 3D")
    , ("fast_part_4", "Fast Part 4")
    , ("fast_part_4a", "Fast Part 4A")
    , ("fast_part_4b", "Fast Part 4B")
    , ("fast_part_4c", "Fast Part 4C")
    , ("fast_part_4d", "Fast Part 4D")
    , ("quiet_part", "Quiet Part")
    , ("quiet_part_a", "Quiet Part A")
    , ("quiet_part_b", "Quiet Part B")
    , ("quiet_part_c", "Quiet Part C")
    , ("quiet_part_d", "Quiet Part D")
    , ("quiet_part_1", "Quiet Part 1")
    , ("quiet_part_1a", "Quiet Part 1A")
    , ("quiet_part_1b", "Quiet Part 1B")
    , ("quiet_part_1c", "Quiet Part 1C")
    , ("quiet_part_1d", "Quiet Part 1D")
    , ("quiet_part_2", "Quiet Part 2")
    , ("quiet_part_2a", "Quiet Part 2A")
    , ("quiet_part_2b", "Quiet Part 2B")
    , ("quiet_part_2c", "Quiet Part 2C")
    , ("quiet_part_2d", "Quiet Part 2D")
    , ("quiet_part_3", "Quiet Part 3")
    , ("quiet_part_3a", "Quiet Part 3A")
    , ("quiet_part_3b", "Quiet Part 3B")
    , ("quiet_part_3c", "Quiet Part 3C")
    , ("quiet_part_3d", "Quiet Part 3D")
    , ("quiet_part_4", "Quiet Part 4")
    , ("quiet_part_4a", "Quiet Part 4A")
    , ("quiet_part_4b", "Quiet Part 4B")
    , ("quiet_part_4c", "Quiet Part 4C")
    , ("quiet_part_4d", "Quiet Part 4D")
    , ("loud_part", "Loud Part")
    , ("loud_part_a", "Loud Part A")
    , ("loud_part_b", "Loud Part B")
    , ("loud_part_c", "Loud Part C")
    , ("loud_part_d", "Loud Part D")
    , ("loud_part_1", "Loud Part 1")
    , ("loud_part_1a", "Loud Part 1A")
    , ("loud_part_1b", "Loud Part 1B")
    , ("loud_part_1c", "Loud Part 1C")
    , ("loud_part_1d", "Loud Part 1D")
    , ("loud_part_2", "Loud Part 2")
    , ("loud_part_2a", "Loud Part 2A")
    , ("loud_part_2b", "Loud Part 2B")
    , ("loud_part_2c", "Loud Part 2C")
    , ("loud_part_2d", "Loud Part 2D")
    , ("loud_part_3", "Loud Part 3")
    , ("loud_part_3a", "Loud Part 3A")
    , ("loud_part_3b", "Loud Part 3B")
    , ("loud_part_3c", "Loud Part 3C")
    , ("loud_part_3d", "Loud Part 3D")
    , ("loud_part_4", "Loud Part 4")
    , ("loud_part_4a", "Loud Part 4A")
    , ("loud_part_4b", "Loud Part 4B")
    , ("loud_part_4c", "Loud Part 4C")
    , ("loud_part_4d", "Loud Part 4D")
    , ("heavy_part", "Heavy Part")
    , ("heavy_part_a", "Heavy Part A")
    , ("heavy_part_b", "Heavy Part B")
    , ("heavy_part_c", "Heavy Part C")
    , ("heavy_part_d", "Heavy Part D")
    , ("heavy_part_1", "Heavy Part 1")
    , ("heavy_part_1a", "Heavy Part 1A")
    , ("heavy_part_1b", "Heavy Part 1B")
    , ("heavy_part_1c", "Heavy Part 1C")
    , ("heavy_part_1d", "Heavy Part 1D")
    , ("heavy_part_2", "Heavy Part 2")
    , ("heavy_part_2a", "Heavy Part 2A")
    , ("heavy_part_2b", "Heavy Part 2B")
    , ("heavy_part_2c", "Heavy Part 2C")
    , ("heavy_part_2d", "Heavy Part 2D")
    , ("heavy_part_3", "Heavy Part 3")
    , ("heavy_part_3a", "Heavy Part 3A")
    , ("heavy_part_3b", "Heavy Part 3B")
    , ("heavy_part_3c", "Heavy Part 3C")
    , ("heavy_part_3d", "Heavy Part 3D")
    , ("heavy_part_4", "Heavy Part 4")
    , ("heavy_part_4a", "Heavy Part 4A")
    , ("heavy_part_4b", "Heavy Part 4B")
    , ("heavy_part_4c", "Heavy Part 4C")
    , ("heavy_part_4d", "Heavy Part 4D")
    , ("spacey", "Spacey Part")
    , ("spacey_part_a", "Spacey Part A")
    , ("spacey_part_b", "Spacey Part B")
    , ("spacey_part_c", "Spacey Part C")
    , ("spacey_part_d", "Spacey Part D")
    , ("spacey_part_1", "Spacey Part 1")
    , ("spacey_part_1a", "Spacey Part 1A")
    , ("spacey_part_1b", "Spacey Part 1B")
    , ("spacey_part_1c", "Spacey Part 1C")
    , ("spacey_part_1d", "Spacey Part 1D")
    , ("spacey_part_2", "Spacey Part 2")
    , ("spacey_part_2a", "Spacey Part 2A")
    , ("spacey_part_2b", "Spacey Part 2B")
    , ("spacey_part_2c", "Spacey Part 2C")
    , ("spacey_part_2d", "Spacey Part 2D")
    , ("spacey_part_3", "Spacey Part 3")
    , ("spacey_part_3a", "Spacey Part 3A")
    , ("spacey_part_3b", "Spacey Part 3B")
    , ("spacey_part_3c", "Spacey Part 3C")
    , ("spacey_part_3d", "Spacey Part 3D")
    , ("spacey_part_4", "Spacey Part 4")
    , ("spacey_part_4a", "Spacey Part 4A")
    , ("spacey_part_4b", "Spacey Part 4B")
    , ("spacey_part_4c", "Spacey Part 4C")
    , ("spacey_part_4d", "Spacey Part 4D")
    , ("trippy_part", "Trippy Part")
    , ("trippy_part_a", "Trippy Part A")
    , ("trippy_part_b", "Trippy Part B")
    , ("trippy_part_c", "Trippy Part C")
    , ("trippy_part_d", "Trippy Part D")
    , ("trippy_part_1", "Trippy Part 1")
    , ("trippy_part_1a", "Trippy Part 1A")
    , ("trippy_part_1b", "Trippy Part 1B")
    , ("trippy_part_1c", "Trippy Part 1C")
    , ("trippy_part_1d", "Trippy Part 1D")
    , ("trippy_part_2", "Trippy Part 2")
    , ("trippy_part_2a", "Trippy Part 2A")
    , ("trippy_part_2b", "Trippy Part 2B")
    , ("trippy_part_2c", "Trippy Part 2C")
    , ("trippy_part_2d", "Trippy Part 2D")
    , ("trippy_part_3", "Trippy Part 3")
    , ("trippy_part_3a", "Trippy Part 3A")
    , ("trippy_part_3b", "Trippy Part 3B")
    , ("trippy_part_3c", "Trippy Part 3C")
    , ("trippy_part_3d", "Trippy Part 3D")
    , ("trippy_part_4", "Trippy Part 4")
    , ("trippy_part_4a", "Trippy Part 4A")
    , ("trippy_part_4b", "Trippy Part 4B")
    , ("trippy_part_4c", "Trippy Part 4C")
    , ("trippy_part_4d", "Trippy Part 4D")
    , ("break", "Break")
    , ("break_a", "Break A")
    , ("break_b", "Break B")
    , ("break_c", "Break C")
    , ("break_d", "Break D")
    , ("break_1", "Break 1")
    , ("break_1a", "Break 1A")
    , ("break_1b", "Break 1B")
    , ("break_1c", "Break 1C")
    , ("break_1d", "Break 1D")
    , ("break_2", "Break 2")
    , ("break_2a", "Break 2A")
    , ("break_2b", "Break 2B")
    , ("break_2c", "Break 2C")
    , ("break_2d", "Break 2D")
    , ("break_3", "Break 3")
    , ("break_3a", "Break 3A")
    , ("break_3b", "Break 3B")
    , ("break_3c", "Break 3C")
    , ("break_3d", "Break 3D")
    , ("break_4", "Break 4")
    , ("break_4a", "Break 4A")
    , ("break_4b", "Break 4B")
    , ("break_4c", "Break 4C")
    , ("break_4d", "Break 4D")
    , ("breakdown", "Breakdown")
    , ("breakdown_a", "Breakdown A")
    , ("breakdown_b", "Breakdown B")
    , ("breakdown_c", "Breakdown C")
    , ("breakdown_d", "Breakdown D")
    , ("breakdown_1", "Breakdown 1")
    , ("breakdown_1a", "Breakdown 1A")
    , ("breakdown_1b", "Breakdown 1B")
    , ("breakdown_1c", "Breakdown 1C")
    , ("breakdown_1d", "Breakdown 1D")
    , ("breakdown_2", "Breakdown 2")
    , ("breakdown_2a", "Breakdown 2A")
    , ("breakdown_2b", "Breakdown 2B")
    , ("breakdown_2c", "Breakdown 2C")
    , ("breakdown_2d", "Breakdown 2D")
    , ("breakdown_3", "Breakdown 3")
    , ("breakdown_3a", "Breakdown 3A")
    , ("breakdown_3b", "Breakdown 3B")
    , ("breakdown_3c", "Breakdown 3C")
    , ("breakdown_3d", "Breakdown 3D")
    , ("breakdown_4", "Breakdown 4")
    , ("breakdown_4a", "Breakdown 4A")
    , ("breakdown_4b", "Breakdown 4B")
    , ("breakdown_4c", "Breakdown 4C")
    , ("breakdown_4d", "Breakdown 4D")
    , ("gtr_break", "Gtr Break")
    , ("gtr_break_a", "Gtr Break A")
    , ("gtr_break_b", "Gtr Break B")
    , ("gtr_break_c", "Gtr Break C")
    , ("gtr_break_d", "Gtr Break D")
    , ("gtr_break_1", "Gtr Break 1")
    , ("gtr_break_1a", "Gtr Break 1A")
    , ("gtr_break_1b", "Gtr Break 1B")
    , ("gtr_break_1c", "Gtr Break 1C")
    , ("gtr_break_1d", "Gtr Break 1D")
    , ("gtr_break_2", "Gtr Break 2")
    , ("gtr_break_2a", "Gtr Break 2A")
    , ("gtr_break_2b", "Gtr Break 2B")
    , ("gtr_break_2c", "Gtr Break 2C")
    , ("gtr_break_2d", "Gtr Break 2D")
    , ("gtr_break_3", "Gtr Break 3")
    , ("gtr_break_3a", "Gtr Break 3A")
    , ("gtr_break_3b", "Gtr Break 3B")
    , ("gtr_break_3c", "Gtr Break 3C")
    , ("gtr_break_3d", "Gtr Break 3D")
    , ("gtr_break_4", "Gtr Break 4")
    , ("gtr_break_4a", "Gtr Break 4A")
    , ("gtr_break_4b", "Gtr Break 4B")
    , ("gtr_break_4c", "Gtr Break 4C")
    , ("gtr_break_4d", "Gtr Break 4D")
    , ("bass_break", "Bass Break")
    , ("bass_break_a", "Bass Break A")
    , ("bass_break_b", "Bass Break B")
    , ("bass_break_c", "Bass Break C")
    , ("bass_break_d", "Bass Break D")
    , ("bass_break_1", "Bass Break 1")
    , ("bass_break_1a", "Bass Break 1A")
    , ("bass_break_1b", "Bass Break 1B")
    , ("bass_break_1c", "Bass Break 1C")
    , ("bass_break_1d", "Bass Break 1D")
    , ("bass_break_2", "Bass Break 2")
    , ("bass_break_2a", "Bass Break 2A")
    , ("bass_break_2b", "Bass Break 2B")
    , ("bass_break_2c", "Bass Break 2C")
    , ("bass_break_2d", "Bass Break 2D")
    , ("bass_break_3", "Bass Break 3")
    , ("bass_break_3a", "Bass Break 3A")
    , ("bass_break_3b", "Bass Break 3B")
    , ("bass_break_3c", "Bass Break 3C")
    , ("bass_break_3d", "Bass Break 3D")
    , ("bass_break_4", "Bass Break 4")
    , ("bass_break_4a", "Bass Break 4A")
    , ("bass_break_4b", "Bass Break 4B")
    , ("bass_break_4c", "Bass Break 4C")
    , ("bass_break_4d", "Bass Break 4D")
    , ("drum_break", "Drum Break")
    , ("drum_break_a", "Drum Break A")
    , ("drum_break_b", "Drum Break B")
    , ("drum_break_c", "Drum Break C")
    , ("drum_break_d", "Drum Break D")
    , ("drum_break_1", "Drum Break 1")
    , ("drum_break_1a", "Drum Break 1A")
    , ("drum_break_1b", "Drum Break 1B")
    , ("drum_break_1c", "Drum Break 1C")
    , ("drum_break_1d", "Drum Break 1D")
    , ("drum_break_2", "Drum Break 2")
    , ("drum_break_2a", "Drum Break 2A")
    , ("drum_break_2b", "Drum Break 2B")
    , ("drum_break_2c", "Drum Break 2C")
    , ("drum_break_2d", "Drum Break 2D")
    , ("drum_break_3", "Drum Break 3")
    , ("drum_break_3a", "Drum Break 3A")
    , ("drum_break_3b", "Drum Break 3B")
    , ("drum_break_3c", "Drum Break 3C")
    , ("drum_break_3d", "Drum Break 3D")
    , ("drum_break_4", "Drum Break 4")
    , ("drum_break_4a", "Drum Break 4A")
    , ("drum_break_4b", "Drum Break 4B")
    , ("drum_break_4c", "Drum Break 4C")
    , ("drum_break_4d", "Drum Break 4D")
    , ("organ_break", "Organ Break")
    , ("organ_break_a", "Organ Break A")
    , ("organ_break_b", "Organ Break B")
    , ("organ_break_c", "Organ Break C")
    , ("organ_break_d", "Organ Break D")
    , ("organ_break_1", "Organ Break 1")
    , ("organ_break_1a", "Organ Break 1A")
    , ("organ_break_1b", "Organ Break 1B")
    , ("organ_break_1c", "Organ Break 1C")
    , ("organ_break_1d", "Organ Break 1D")
    , ("organ_break_2", "Organ Break 2")
    , ("organ_break_2a", "Organ Break 2A")
    , ("organ_break_2b", "Organ Break 2B")
    , ("organ_break_2c", "Organ Break 2C")
    , ("organ_break_2d", "Organ Break 2D")
    , ("organ_break_3", "Organ Break 3")
    , ("organ_break_3a", "Organ Break 3A")
    , ("organ_break_3b", "Organ Break 3B")
    , ("organ_break_3c", "Organ Break 3C")
    , ("organ_break_3d", "Organ Break 3D")
    , ("organ_break_4", "Organ Break 4")
    , ("organ_break_4a", "Organ Break 4A")
    , ("organ_break_4b", "Organ Break 4B")
    , ("organ_break_4c", "Organ Break 4C")
    , ("organ_break_4d", "Organ Break 4D")
    , ("synth_break", "Synth Break")
    , ("synth_break_a", "Synth Break A")
    , ("synth_break_b", "Synth Break B")
    , ("synth_break_c", "Synth Break C")
    , ("synth_break_d", "Synth Break D")
    , ("synth_break_1", "Synth Break 1")
    , ("synth_break_1a", "Synth Break 1A")
    , ("synth_break_1b", "Synth Break 1B")
    , ("synth_break_1c", "Synth Break 1C")
    , ("synth_break_1d", "Synth Break 1D")
    , ("synth_break_2", "Synth Break 2")
    , ("synth_break_2a", "Synth Break 2A")
    , ("synth_break_2b", "Synth Break 2B")
    , ("synth_break_2c", "Synth Break 2C")
    , ("synth_break_2d", "Synth Break 2D")
    , ("synth_break_3", "Synth Break 3")
    , ("synth_break_3a", "Synth Break 3A")
    , ("synth_break_3b", "Synth Break 3B")
    , ("synth_break_3c", "Synth Break 3C")
    , ("synth_break_3d", "Synth Break 3D")
    , ("synth_break_4", "Synth Break 4")
    , ("synth_break_4a", "Synth Break 4A")
    , ("synth_break_4b", "Synth Break 4B")
    , ("synth_break_4c", "Synth Break 4C")
    , ("synth_break_4d", "Synth Break 4D")
    , ("piano_break", "Piano Break")
    , ("piano_break_a", "Piano Break A")
    , ("piano_break_b", "Piano Break B")
    , ("piano_break_c", "Piano Break C")
    , ("piano_break_d", "Piano Break D")
    , ("piano_break_1", "Piano Break 1")
    , ("piano_break_1a", "Piano Break 1A")
    , ("piano_break_1b", "Piano Break 1B")
    , ("piano_break_1c", "Piano Break 1C")
    , ("piano_break_1d", "Piano Break 1D")
    , ("piano_break_2", "Piano Break 2")
    , ("piano_break_2a", "Piano Break 2A")
    , ("piano_break_2b", "Piano Break 2B")
    , ("piano_break_2c", "Piano Break 2C")
    , ("piano_break_2d", "Piano Break 2D")
    , ("piano_break_3", "Piano Break 3")
    , ("piano_break_3a", "Piano Break 3A")
    , ("piano_break_3b", "Piano Break 3B")
    , ("piano_break_3c", "Piano Break 3C")
    , ("piano_break_3d", "Piano Break 3D")
    , ("piano_break_4", "Piano Break 4")
    , ("piano_break_4a", "Piano Break 4A")
    , ("piano_break_4b", "Piano Break 4B")
    , ("piano_break_4c", "Piano Break 4C")
    , ("piano_break_4d", "Piano Break 4D")
    , ("keyboard_break", "Keyboard Break")
    , ("keyboard_break_a", "Keyboard Break A")
    , ("keyboard_break_b", "Keyboard Break B")
    , ("keyboard_break_c", "Keyboard Break C")
    , ("keyboard_break_d", "Keyboard Break D")
    , ("keyboard_break_1", "Keyboard Break 1")
    , ("keyboard_break_1a", "Keyboard Break 1A")
    , ("keyboard_break_1b", "Keyboard Break 1B")
    , ("keyboard_break_1c", "Keyboard Break 1C")
    , ("keyboard_break_1d", "Keyboard Break 1D")
    , ("keyboard_break_2", "Keyboard Break 2")
    , ("keyboard_break_2a", "Keyboard Break 2A")
    , ("keyboard_break_2b", "Keyboard Break 2B")
    , ("keyboard_break_2c", "Keyboard Break 2C")
    , ("keyboard_break_2d", "Keyboard Break 2D")
    , ("keyboard_break_3", "Keyboard Break 3")
    , ("keyboard_break_3a", "Keyboard Break 3A")
    , ("keyboard_break_3b", "Keyboard Break 3B")
    , ("keyboard_break_3c", "Keyboard Break 3C")
    , ("keyboard_break_3d", "Keyboard Break 3D")
    , ("keyboard_break_4", "Keyboard Break 4")
    , ("keyboard_break_4a", "Keyboard Break 4A")
    , ("keyboard_break_4b", "Keyboard Break 4B")
    , ("keyboard_break_4c", "Keyboard Break 4C")
    , ("keyboard_break_4d", "Keyboard Break 4D")
    , ("horn_break", "Horn Break")
    , ("sctrach_break", "Scratch Break") -- is this typo correct?
    , ("perc_break", "Percussion Break")
    , ("dj_break", "DJ Break")
    , ("interlude", "Interlude")
    , ("interlude_a", "Interlude A")
    , ("interlude_b", "Interlude B")
    , ("interlude_c", "Interlude C")
    , ("interlude_d", "Interlude D")
    , ("interlude_1", "Interlude 1")
    , ("interlude_1a", "Interlude 1A")
    , ("interlude_1b", "Interlude 1B")
    , ("interlude_1c", "Interlude 1C")
    , ("interlude_1d", "Interlude 1D")
    , ("interlude_2", "Interlude 2")
    , ("interlude_2a", "Interlude 2A")
    , ("interlude_2b", "Interlude 2B")
    , ("interlude_2c", "Interlude 2C")
    , ("interlude_2d", "Interlude 2D")
    , ("interlude_3", "Interlude 3")
    , ("interlude_3a", "Interlude 3A")
    , ("interlude_3b", "Interlude 3B")
    , ("interlude_3c", "Interlude 3C")
    , ("interlude_3d", "Interlude 3D")
    , ("interlude_4", "Interlude 4")
    , ("interlude_4a", "Interlude 4A")
    , ("interlude_4b", "Interlude 4B")
    , ("interlude_4c", "Interlude 4C")
    , ("interlude_4d", "Interlude 4D")
    , ("soundscape", "Soundscape")
    , ("soundscape_a", "Soundscape A")
    , ("soundscape_b", "Soundscape B")
    , ("soundscape_c", "Soundscape C")
    , ("soundscape_d", "Soundscape D")
    , ("soundscape_1", "Soundscape 1")
    , ("soundscape_1a", "Soundscape 1A")
    , ("soundscape_1b", "Soundscape 1B")
    , ("soundscape_1c", "Soundscape 1C")
    , ("soundscape_1d", "Soundscape 1D")
    , ("soundscape_2", "Soundscape 2")
    , ("soundscape_2a", "Soundscape 2A")
    , ("soundscape_2b", "Soundscape 2B")
    , ("soundscape_2c", "Soundscape 2C")
    , ("soundscape_2d", "Soundscape 2D")
    , ("soundscape_3", "Soundscape 3")
    , ("soundscape_3a", "Soundscape 3A")
    , ("soundscape_3b", "Soundscape 3B")
    , ("soundscape_3c", "Soundscape 3C")
    , ("soundscape_3d", "Soundscape 3D")
    , ("soundscape_4", "Soundscape 4")
    , ("soundscape_4a", "Soundscape 4A")
    , ("soundscape_4b", "Soundscape 4B")
    , ("soundscape_4c", "Soundscape 4C")
    , ("soundscape_4d", "Soundscape 4D")
    , ("jam", "Jam")
    , ("jam_a", "Jam A")
    , ("jam_b", "Jam B")
    , ("jam_c", "Jam C")
    , ("jam_d", "Jam D")
    , ("jam_1", "Jam 1")
    , ("jam_1a", "Jam 1A")
    , ("jam_1b", "Jam 1B")
    , ("jam_1c", "Jam 1C")
    , ("jam_1d", "Jam 1D")
    , ("jam_2", "Jam 2")
    , ("jam_2a", "Jam 2A")
    , ("jam_2b", "Jam 2B")
    , ("jam_2c", "Jam 2C")
    , ("jam_2d", "Jam 2D")
    , ("jam_3", "Jam 3")
    , ("jam_3a", "Jam 3A")
    , ("jam_3b", "Jam 3B")
    , ("jam_3c", "Jam 3C")
    , ("jam_3d", "Jam 3D")
    , ("jam_4", "Jam 4")
    , ("jam_4a", "Jam 4A")
    , ("jam_4b", "Jam 4B")
    , ("jam_4c", "Jam 4C")
    , ("jam_4d", "Jam 4D")
    , ("space_jam", "Space Jam")
    , ("space_jam_a", "Space Jam A")
    , ("space_jam_b", "Space Jam B")
    , ("space_jam_c", "Space Jam C")
    , ("space_jam_d", "Space Jam D")
    , ("space_jam_1", "Space Jam 1")
    , ("space_jam_1a", "Space Jam 1A")
    , ("space_jam_1b", "Space Jam 1B")
    , ("space_jam_1c", "Space Jam 1C")
    , ("space_jam_1d", "Space Jam 1D")
    , ("space_jam_2", "Space Jam 2")
    , ("space_jam_2a", "Space Jam 2A")
    , ("space_jam_2b", "Space Jam 2B")
    , ("space_jam_2c", "Space Jam 2C")
    , ("space_jam_2d", "Space Jam 2D")
    , ("space_jam_3", "Space Jam 3")
    , ("space_jam_3a", "Space Jam 3A")
    , ("space_jam_3b", "Space Jam 3B")
    , ("space_jam_3c", "Space Jam 3C")
    , ("space_jam_3d", "Space Jam 3D")
    , ("space_jam_4", "Space Jam 4")
    , ("space_jam_4a", "Space Jam 4A")
    , ("space_jam_4b", "Space Jam 4B")
    , ("space_jam_4c", "Space Jam 4C")
    , ("space_jam_4d", "Space Jam 4D")
    , ("vamp", "Vamp")
    , ("vamp_a", "Vamp A")
    , ("vamp_b", "Vamp B")
    , ("vamp_c", "Vamp C")
    , ("vamp_d", "Vamp D")
    , ("vamp_1", "Vamp 1")
    , ("vamp_1a", "Vamp 1A")
    , ("vamp_1b", "Vamp 1B")
    , ("vamp_1c", "Vamp 1C")
    , ("vamp_1d", "Vamp 1D")
    , ("vamp_2", "Vamp 2")
    , ("vamp_2a", "Vamp 2A")
    , ("vamp_2b", "Vamp 2B")
    , ("vamp_2c", "Vamp 2C")
    , ("vamp_2d", "Vamp 2D")
    , ("vamp_3", "Vamp 3")
    , ("vamp_3a", "Vamp 3A")
    , ("vamp_3b", "Vamp 3B")
    , ("vamp_3c", "Vamp 3C")
    , ("vamp_3d", "Vamp 3D")
    , ("vamp_4", "Vamp 4")
    , ("vamp_4a", "Vamp 4A")
    , ("vamp_4b", "Vamp 4B")
    , ("vamp_4c", "Vamp 4C")
    , ("vamp_4d", "Vamp 4D")
    , ("build_up", "Build Up")
    , ("build_up_a", "Build Up A")
    , ("build_up_b", "Build Up B")
    , ("build_up_c", "Build Up C")
    , ("build_up_d", "Build Up D")
    , ("build_up_1", "Build Up 1")
    , ("build_up_1a", "Build Up 1A")
    , ("build_up_1b", "Build Up 1B")
    , ("build_up_1c", "Build Up 1C")
    , ("build_up_1d", "Build Up 1D")
    , ("build_up_2", "Build Up 2")
    , ("build_up_2a", "Build Up 2A")
    , ("build_up_2b", "Build Up 2B")
    , ("build_up_2c", "Build Up 2C")
    , ("build_up_2d", "Build Up 2D")
    , ("build_up_3", "Build Up 3")
    , ("build_up_3a", "Build Up 3A")
    , ("build_up_3b", "Build Up 3B")
    , ("build_up_3c", "Build Up 3C")
    , ("build_up_3d", "Build Up 3D")
    , ("build_up_4", "Build Up 4")
    , ("build_up_4a", "Build Up 4A")
    , ("build_up_4b", "Build Up 4B")
    , ("build_up_4c", "Build Up 4C")
    , ("build_up_4d", "Build Up 4D")
    , ("speedup", "Speed Up")
    , ("speed_up_a", "Speed Up A")
    , ("speed_up_b", "Speed Up B")
    , ("speed_up_c", "Speed Up C")
    , ("speed_up_d", "Speed Up D")
    , ("speed_up_1", "Speed Up 1")
    , ("speed_up_1a", "Speed Up 1A")
    , ("speed_up_1b", "Speed Up 1B")
    , ("speed_up_1c", "Speed Up 1C")
    , ("speed_up_1d", "Speed Up 1D")
    , ("speed_up_2", "Speed Up 2")
    , ("speed_up_2a", "Speed Up 2A")
    , ("speed_up_2b", "Speed Up 2B")
    , ("speed_up_2c", "Speed Up 2C")
    , ("speed_up_2d", "Speed Up 2D")
    , ("speed_up_3", "Speed Up 3")
    , ("speed_up_3a", "Speed Up 3A")
    , ("speed_up_3b", "Speed Up 3B")
    , ("speed_up_3c", "Speed Up 3C")
    , ("speed_up_3d", "Speed Up 3D")
    , ("speed_up_4", "Speed Up 4")
    , ("speed_up_4a", "Speed Up 4A")
    , ("speed_up_4b", "Speed Up 4B")
    , ("speed_up_4c", "Speed Up 4C")
    , ("speed_up_4d", "Speed Up 4D")
    , ("tension", "Tension")
    , ("tension_a", "Tension A")
    , ("tension_b", "Tension B")
    , ("tension_c", "Tension C")
    , ("tension_d", "Tension D")
    , ("tension_1", "Tension 1")
    , ("tension_1a", "Tension 1A")
    , ("tension_1b", "Tension 1B")
    , ("tension_1c", "Tension 1C")
    , ("tension_1d", "Tension 1D")
    , ("tension_2", "Tension 2")
    , ("tension_2a", "Tension 2A")
    , ("tension_2b", "Tension 2B")
    , ("tension_2c", "Tension 2C")
    , ("tension_2d", "Tension 2D")
    , ("tension_3", "Tension 3")
    , ("tension_3a", "Tension 3A")
    , ("tension_3b", "Tension 3B")
    , ("tension_3c", "Tension 3C")
    , ("tension_3d", "Tension 3D")
    , ("tension_4", "Tension 4")
    , ("tension_4a", "Tension 4A")
    , ("tension_4b", "Tension 4B")
    , ("tension_4c", "Tension 4C")
    , ("tension_4d", "Tension 4D")
    , ("release", "Release")
    , ("release_a", "Release A")
    , ("release_b", "Release B")
    , ("release_c", "Release C")
    , ("release_d", "Release D")
    , ("release_1", "Release 1")
    , ("release_1a", "Release 1A")
    , ("release_1b", "Release 1B")
    , ("release_1c", "Release 1C")
    , ("release_1d", "Release 1D")
    , ("release_2", "Release 2")
    , ("release_2a", "Release 2A")
    , ("release_2b", "Release 2B")
    , ("release_2c", "Release 2C")
    , ("release_2d", "Release 2D")
    , ("release_3", "Release 3")
    , ("release_3a", "Release 3A")
    , ("release_3b", "Release 3B")
    , ("release_3c", "Release 3C")
    , ("release_3d", "Release 3D")
    , ("release_4", "Release 4")
    , ("release_4a", "Release 4A")
    , ("release_4b", "Release 4B")
    , ("release_4c", "Release 4C")
    , ("release_4d", "Release 4D")
    , ("crescendo", "Crescendo")
    , ("crescendo_a", "Crescendo A")
    , ("crescendo_b", "Crescendo B")
    , ("crescendo_c", "Crescendo C")
    , ("crescendo_d", "Crescendo D")
    , ("crescendo_1", "Crescendo 1")
    , ("crescendo_1a", "Crescendo 1A")
    , ("crescendo_1b", "Crescendo 1B")
    , ("crescendo_1c", "Crescendo 1C")
    , ("crescendo_1d", "Crescendo 1D")
    , ("crescendo_2", "Crescendo 2")
    , ("crescendo_2a", "Crescendo 2A")
    , ("crescendo_2b", "Crescendo 2B")
    , ("crescendo_2c", "Crescendo 2C")
    , ("crescendo_2d", "Crescendo 2D")
    , ("crescendo_3", "Crescendo 3")
    , ("crescendo_3a", "Crescendo 3A")
    , ("crescendo_3b", "Crescendo 3B")
    , ("crescendo_3c", "Crescendo 3C")
    , ("crescendo_3d", "Crescendo 3D")
    , ("crescendo_4", "Crescendo 4")
    , ("crescendo_4a", "Crescendo 4A")
    , ("crescendo_4b", "Crescendo 4B")
    , ("crescendo_4c", "Crescendo 4C")
    , ("crescendo_4d", "Crescendo 4D")
    , ("melody", "Melody")
    , ("melody_a", "Melody A")
    , ("melody_b", "Melody B")
    , ("melody_c", "Melody C")
    , ("melody_d", "Melody D")
    , ("melody_1", "Melody 1")
    , ("melody_1a", "Melody 1A")
    , ("melody_1b", "Melody 1B")
    , ("melody_1c", "Melody 1C")
    , ("melody_1d", "Melody 1D")
    , ("melody_2", "Melody 2")
    , ("melody_2a", "Melody 2A")
    , ("melody_2b", "Melody 2B")
    , ("melody_2c", "Melody 2C")
    , ("melody_2d", "Melody 2D")
    , ("melody_3", "Melody 3")
    , ("melody_3a", "Melody 3A")
    , ("melody_3b", "Melody 3B")
    , ("melody_3c", "Melody 3C")
    , ("melody_3d", "Melody 3D")
    , ("melody_4", "Melody 4")
    , ("melody_4a", "Melody 4A")
    , ("melody_4b", "Melody 4B")
    , ("melody_4c", "Melody 4C")
    , ("melody_4d", "Melody 4D")
    , ("lo_melody", "Low Melody")
    , ("lo_melody_a", "Low Melody A")
    , ("lo_melody_b", "Low Melody B")
    , ("lo_melody_c", "Low Melody C")
    , ("lo_melody_d", "Low Melody D")
    , ("lo_melody_1", "Low Melody 1")
    , ("lo_melody_1a", "Low Melody 1A")
    , ("lo_melody_1b", "Low Melody 1B")
    , ("lo_melody_1c", "Low Melody 1C")
    , ("lo_melody_1d", "Low Melody 1D")
    , ("lo_melody_2", "Low Melody 2")
    , ("lo_melody_2a", "Low Melody 2A")
    , ("lo_melody_2b", "Low Melody 2B")
    , ("lo_melody_2c", "Low Melody 2C")
    , ("lo_melody_2d", "Low Melody 2D")
    , ("lo_melody_3", "Low Melody 3")
    , ("lo_melody_3a", "Low Melody 3A")
    , ("lo_melody_3b", "Low Melody 3B")
    , ("lo_melody_3c", "Low Melody 3C")
    , ("lo_melody_3d", "Low Melody 3D")
    , ("lo_melody_4", "Low Melody 4")
    , ("lo_melody_4a", "Low Melody 4A")
    , ("lo_melody_4b", "Low Melody 4B")
    , ("lo_melody_4c", "Low Melody 4C")
    , ("lo_melody_4d", "Low Melody 4D")
    , ("hi_melody", "High Melody")
    , ("hi_melody_a", "High Melody A")
    , ("hi_melody_b", "High Melody B")
    , ("hi_melody_c", "High Melody C")
    , ("hi_melody_d", "High Melody D")
    , ("hi_melody_1", "High Melody 1")
    , ("hi_melody_1a", "High Melody 1A")
    , ("hi_melody_1b", "High Melody 1B")
    , ("hi_melody_1c", "High Melody 1C")
    , ("hi_melody_1d", "High Melody 1D")
    , ("hi_melody_2", "High Melody 2")
    , ("hi_melody_2a", "High Melody 2A")
    , ("hi_melody_2b", "High Melody 2B")
    , ("hi_melody_2c", "High Melody 2C")
    , ("hi_melody_2d", "High Melody 2D")
    , ("hi_melody_3", "High Melody 3")
    , ("hi_melody_3a", "High Melody 3A")
    , ("hi_melody_3b", "High Melody 3B")
    , ("hi_melody_3c", "High Melody 3C")
    , ("hi_melody_3d", "High Melody 3D")
    , ("hi_melody_4", "High Melody 4")
    , ("hi_melody_4a", "High Melody 4A")
    , ("hi_melody_4b", "High Melody 4B")
    , ("hi_melody_4c", "High Melody 4C")
    , ("hi_melody_4d", "High Melody 4D")
    , ("main_riff", "Main Riff")
    , ("main_riff_a", "Main Riff A")
    , ("main_riff_b", "Main Riff B")
    , ("main_riff_c", "Main Riff C")
    , ("main_riff_d", "Main Riff D")
    , ("main_riff_e", "Main Riff E")
    , ("main_riff_f", "Main Riff F")
    , ("main_riff_1", "Main Riff 1")
    , ("main_riff_1a", "Main Riff 1A")
    , ("main_riff_1b", "Main Riff 1B")
    , ("main_riff_1c", "Main Riff 1C")
    , ("main_riff_1d", "Main Riff 1D")
    , ("main_riff_1e", "Main Riff 1E")
    , ("main_riff_1f", "Main Riff 1F")
    , ("main_riff_2", "Main Riff 2")
    , ("main_riff_2a", "Main Riff 2A")
    , ("main_riff_2b", "Main Riff 2B")
    , ("main_riff_2c", "Main Riff 2C")
    , ("main_riff_2d", "Main Riff 2D")
    , ("main_riff_2e", "Main Riff 2E")
    , ("main_riff_2f", "Main Riff 2F")
    , ("main_riff_3", "Main Riff 3")
    , ("main_riff_3a", "Main Riff 3A")
    , ("main_riff_3b", "Main Riff 3B")
    , ("main_riff_3c", "Main Riff 3C")
    , ("main_riff_3d", "Main Riff 3D")
    , ("main_riff_3e", "Main Riff 3E")
    , ("main_riff_3f", "Main Riff 3F")
    , ("main_riff_4", "Main Riff 4")
    , ("main_riff_4a", "Main Riff 4A")
    , ("main_riff_4b", "Main Riff 4B")
    , ("main_riff_4c", "Main Riff 4C")
    , ("main_riff_4d", "Main Riff 4D")
    , ("main_riff_5", "Main Riff 5")
    , ("main_riff_5a", "Main Riff 5A")
    , ("main_riff_5b", "Main Riff 5B")
    , ("main_riff_5c", "Main Riff 5C")
    , ("main_riff_5d", "Main Riff 5D")
    , ("main_riff_6", "Main Riff 6")
    , ("main_riff_6a", "Main Riff 6A")
    , ("main_riff_6b", "Main Riff 6B")
    , ("main_riff_6c", "Main Riff 6C")
    , ("main_riff_6d", "Main Riff 6D")
    , ("main_riff_7", "Main Riff 7")
    , ("main_riff_7a", "Main Riff 7A")
    , ("main_riff_7b", "Main Riff 7B")
    , ("main_riff_7c", "Main Riff 7C")
    , ("main_riff_7d", "Main Riff 7D")
    , ("main_riff_8", "Main Riff 8")
    , ("main_riff_8a", "Main Riff 8A")
    , ("main_riff_8b", "Main Riff 8B")
    , ("main_riff_8c", "Main Riff 8C")
    , ("main_riff_8d", "Main Riff 8D")
    , ("main_riff_9", "Main Riff 9")
    , ("main_riff_9a", "Main Riff 9A")
    , ("main_riff_9b", "Main Riff 9B")
    , ("main_riff_9c", "Main Riff 9C")
    , ("main_riff_9d", "Main Riff 9D")
    , ("verse_riff", "Verse Riff")
    , ("verse_riff_a", "Verse Riff A")
    , ("verse_riff_b", "Verse Riff B")
    , ("verse_riff_c", "Verse Riff C")
    , ("verse_riff_d", "Verse Riff D")
    , ("verse_riff_1", "Verse Riff 1")
    , ("verse_riff_1a", "Verse Riff 1A")
    , ("verse_riff_1b", "Verse Riff 1B")
    , ("verse_riff_1c", "Verse Riff 1C")
    , ("verse_riff_1d", "Verse Riff 1D")
    , ("verse_riff_2", "Verse Riff 2")
    , ("verse_riff_2a", "Verse Riff 2A")
    , ("verse_riff_2b", "Verse Riff 2B")
    , ("verse_riff_2c", "Verse Riff 2C")
    , ("verse_riff_2d", "Verse Riff 2D")
    , ("verse_riff_3", "Verse Riff 3")
    , ("verse_riff_3a", "Verse Riff 3A")
    , ("verse_riff_3b", "Verse Riff 3B")
    , ("verse_riff_3c", "Verse Riff 3C")
    , ("verse_riff_3d", "Verse Riff 3D")
    , ("verse_riff_4", "Verse Riff 4")
    , ("verse_riff_4a", "Verse Riff 4A")
    , ("verse_riff_4b", "Verse Riff 4B")
    , ("verse_riff_4c", "Verse Riff 4C")
    , ("verse_riff_4d", "Verse Riff 4D")
    , ("chorus_riff", "Chorus Riff")
    , ("chorus_riff_a", "Chorus Riff A")
    , ("chorus_riff_b", "Chorus Riff B")
    , ("chorus_riff_c", "Chorus Riff C")
    , ("chorus_riff_d", "Chorus Riff D")
    , ("chorus_riff_1", "Chorus Riff 1")
    , ("chorus_riff_1a", "Chorus Riff 1A")
    , ("chorus_riff_1b", "Chorus Riff 1B")
    , ("chorus_riff_1c", "Chorus Riff 1C")
    , ("chorus_riff_1d", "Chorus Riff 1D")
    , ("chorus_riff_2", "Chorus Riff 2")
    , ("chorus_riff_2a", "Chorus Riff 2A")
    , ("chorus_riff_2b", "Chorus Riff 2B")
    , ("chorus_riff_2c", "Chorus Riff 2C")
    , ("chorus_riff_2d", "Chorus Riff 2D")
    , ("chorus_riff_3", "Chorus Riff 3")
    , ("chorus_riff_3a", "Chorus Riff 3A")
    , ("chorus_riff_3b", "Chorus Riff 3B")
    , ("chorus_riff_3c", "Chorus Riff 3C")
    , ("chorus_riff_3d", "Chorus Riff 3D")
    , ("chorus_riff_4", "Chorus Riff 4")
    , ("chorus_riff_4a", "Chorus Riff 4A")
    , ("chorus_riff_4b", "Chorus Riff 4B")
    , ("chorus_riff_4c", "Chorus Riff 4C")
    , ("chorus_riff_4d", "Chorus Riff 4D")
    , ("gtr_riff", "Gtr Riff")
    , ("gtr_riff_a", "Gtr Riff A")
    , ("gtr_riff_b", "Gtr Riff B")
    , ("gtr_riff_c", "Gtr Riff C")
    , ("gtr_riff_d", "Gtr Riff D")
    , ("gtr_riff_1", "Gtr Riff 1")
    , ("gtr_riff_1a", "Gtr Riff 1A")
    , ("gtr_riff_1b", "Gtr Riff 1B")
    , ("gtr_riff_1c", "Gtr Riff 1C")
    , ("gtr_riff_1d", "Gtr Riff 1D")
    , ("gtr_riff_2", "Gtr Riff 2")
    , ("gtr_riff_2a", "Gtr Riff 2A")
    , ("gtr_riff_2b", "Gtr Riff 2B")
    , ("gtr_riff_2c", "Gtr Riff 2C")
    , ("gtr_riff_2d", "Gtr Riff 2D")
    , ("gtr_riff_3", "Gtr Riff 3")
    , ("gtr_riff_3a", "Gtr Riff 3A")
    , ("gtr_riff_3b", "Gtr Riff 3B")
    , ("gtr_riff_3c", "Gtr Riff 3C")
    , ("gtr_riff_3d", "Gtr Riff 3D")
    , ("gtr_riff_4", "Gtr Riff 4")
    , ("gtr_riff_4a", "Gtr Riff 4A")
    , ("gtr_riff_4b", "Gtr Riff 4B")
    , ("gtr_riff_4c", "Gtr Riff 4C")
    , ("gtr_riff_4d", "Gtr Riff 4D")
    , ("bass_riff", "Bass Riff")
    , ("bass_riff_a", "Bass Riff A")
    , ("bass_riff_b", "Bass Riff B")
    , ("bass_riff_c", "Bass Riff C")
    , ("bass_riff_d", "Bass Riff D")
    , ("bass_riff_1", "Bass Riff 1")
    , ("bass_riff_1a", "Bass Riff 1A")
    , ("bass_riff_1b", "Bass Riff 1B")
    , ("bass_riff_1c", "Bass Riff 1C")
    , ("bass_riff_1d", "Bass Riff 1D")
    , ("bass_riff_2", "Bass Riff 2")
    , ("bass_riff_2a", "Bass Riff 2A")
    , ("bass_riff_2b", "Bass Riff 2B")
    , ("bass_riff_2c", "Bass Riff 2C")
    , ("bass_riff_2d", "Bass Riff 2D")
    , ("bass_riff_3", "Bass Riff 3")
    , ("bass_riff_3a", "Bass Riff 3A")
    , ("bass_riff_3b", "Bass Riff 3B")
    , ("bass_riff_3c", "Bass Riff 3C")
    , ("bass_riff_3d", "Bass Riff 3D")
    , ("bass_riff_4", "Bass Riff 4")
    , ("bass_riff_4a", "Bass Riff 4A")
    , ("bass_riff_4b", "Bass Riff 4B")
    , ("bass_riff_4c", "Bass Riff 4C")
    , ("bass_riff_4d", "Bass Riff 4D")
    , ("big_riff", "Big Riff")
    , ("big_riff_a", "Big Riff A")
    , ("big_riff_b", "Big Riff B")
    , ("big_riff_c", "Big Riff C")
    , ("big_riff_d", "Big Riff D")
    , ("big_riff_1", "Big Riff 1")
    , ("big_riff_1a", "Big Riff 1A")
    , ("big_riff_1b", "Big Riff 1B")
    , ("big_riff_1c", "Big Riff 1C")
    , ("big_riff_1d", "Big Riff 1D")
    , ("big_riff_2", "Big Riff 2")
    , ("big_riff_2a", "Big Riff 2A")
    , ("big_riff_2b", "Big Riff 2B")
    , ("big_riff_2c", "Big Riff 2C")
    , ("big_riff_2d", "Big Riff 2D")
    , ("big_riff_3", "Big Riff 3")
    , ("big_riff_3a", "Big Riff 3A")
    , ("big_riff_3b", "Big Riff 3B")
    , ("big_riff_3c", "Big Riff 3C")
    , ("big_riff_3d", "Big Riff 3D")
    , ("big_riff_4", "Big Riff 4")
    , ("big_riff_4a", "Big Riff 4A")
    , ("big_riff_4b", "Big Riff 4B")
    , ("big_riff_4c", "Big Riff 4C")
    , ("big_riff_4d", "Big Riff 4D")
    , ("bigger_riff", "Bigger Riff")
    , ("bigger_riff_a", "Bigger Riff A")
    , ("bigger_riff_b", "Bigger Riff B")
    , ("bigger_riff_c", "Bigger Riff C")
    , ("bigger_riff_d", "Bigger Riff D")
    , ("bigger_riff_1", "Bigger Riff 1")
    , ("bigger_riff_1a", "Bigger Riff 1A")
    , ("bigger_riff_1b", "Bigger Riff 1B")
    , ("bigger_riff_1c", "Bigger Riff 1C")
    , ("bigger_riff_1d", "Bigger Riff 1D")
    , ("bigger_riff_2", "Bigger Riff 2")
    , ("bigger_riff_2a", "Bigger Riff 2A")
    , ("bigger_riff_2b", "Bigger Riff 2B")
    , ("bigger_riff_2c", "Bigger Riff 2C")
    , ("bigger_riff_2d", "Bigger Riff 2D")
    , ("bigger_riff_3", "Bigger Riff 3")
    , ("bigger_riff_3a", "Bigger Riff 3A")
    , ("bigger_riff_3b", "Bigger Riff 3B")
    , ("bigger_riff_3c", "Bigger Riff 3C")
    , ("bigger_riff_3d", "Bigger Riff 3D")
    , ("bigger_riff_4", "Bigger Riff 4")
    , ("bigger_riff_4a", "Bigger Riff 4A")
    , ("bigger_riff_4b", "Bigger Riff 4B")
    , ("bigger_riff_4c", "Bigger Riff 4C")
    , ("bigger_riff_4d", "Bigger Riff 4D")
    , ("heavy_riff", "Heavy Riff")
    , ("heavy_riff_a", "Heavy Riff A")
    , ("heavy_riff_b", "Heavy Riff B")
    , ("heavy_riff_c", "Heavy Riff C")
    , ("heavy_riff_d", "Heavy Riff D")
    , ("heavy_riff_1", "Heavy Riff 1")
    , ("heavy_riff_1a", "Heavy Riff 1A")
    , ("heavy_riff_1b", "Heavy Riff 1B")
    , ("heavy_riff_1c", "Heavy Riff 1C")
    , ("heavy_riff_1d", "Heavy Riff 1D")
    , ("heavy_riff_2", "Heavy Riff 2")
    , ("heavy_riff_2a", "Heavy Riff 2A")
    , ("heavy_riff_2b", "Heavy Riff 2B")
    , ("heavy_riff_2c", "Heavy Riff 2C")
    , ("heavy_riff_2d", "Heavy Riff 2D")
    , ("heavy_riff_3", "Heavy Riff 3")
    , ("heavy_riff_3a", "Heavy Riff 3A")
    , ("heavy_riff_3b", "Heavy Riff 3B")
    , ("heavy_riff_3c", "Heavy Riff 3C")
    , ("heavy_riff_3d", "Heavy Riff 3D")
    , ("heavy_riff_4", "Heavy Riff 4")
    , ("heavy_riff_4a", "Heavy Riff 4A")
    , ("heavy_riff_4b", "Heavy Riff 4B")
    , ("heavy_riff_4c", "Heavy Riff 4C")
    , ("heavy_riff_4d", "Heavy Riff 4D")
    , ("fast_riff", "Fast Riff")
    , ("fast_riff_a", "Fast Riff A")
    , ("fast_riff_b", "Fast Riff B")
    , ("fast_riff_c", "Fast Riff C")
    , ("fast_riff_d", "Fast Riff D")
    , ("fast_riff_1", "Fast Riff 1")
    , ("fast_riff_1a", "Fast Riff 1A")
    , ("fast_riff_1b", "Fast Riff 1B")
    , ("fast_riff_1c", "Fast Riff 1C")
    , ("fast_riff_1d", "Fast Riff 1D")
    , ("fast_riff_2", "Fast Riff 2")
    , ("fast_riff_2a", "Fast Riff 2A")
    , ("fast_riff_2b", "Fast Riff 2B")
    , ("fast_riff_2c", "Fast Riff 2C")
    , ("fast_riff_2d", "Fast Riff 2D")
    , ("fast_riff_3", "Fast Riff 3")
    , ("fast_riff_3a", "Fast Riff 3A")
    , ("fast_riff_3b", "Fast Riff 3B")
    , ("fast_riff_3c", "Fast Riff 3C")
    , ("fast_riff_3d", "Fast Riff 3D")
    , ("fast_riff_4", "Fast Riff 4")
    , ("fast_riff_4a", "Fast Riff 4A")
    , ("fast_riff_4b", "Fast Riff 4B")
    , ("fast_riff_4c", "Fast Riff 4C")
    , ("fast_riff_4d", "Fast Riff 4D")
    , ("slow_riff", "Slow Riff")
    , ("slow_riff_a", "Slow Riff A")
    , ("slow_riff_b", "Slow Riff B")
    , ("slow_riff_c", "Slow Riff C")
    , ("slow_riff_d", "Slow Riff D")
    , ("slow_riff_1", "Slow Riff 1")
    , ("slow_riff_1a", "Slow Riff 1A")
    , ("slow_riff_1b", "Slow Riff 1B")
    , ("slow_riff_1c", "Slow Riff 1C")
    , ("slow_riff_1d", "Slow Riff 1D")
    , ("slow_riff_2", "Slow Riff 2")
    , ("slow_riff_2a", "Slow Riff 2A")
    , ("slow_riff_2b", "Slow Riff 2B")
    , ("slow_riff_2c", "Slow Riff 2C")
    , ("slow_riff_2d", "Slow Riff 2D")
    , ("slow_riff_3", "Slow Riff 3")
    , ("slow_riff_3a", "Slow Riff 3A")
    , ("slow_riff_3b", "Slow Riff 3B")
    , ("slow_riff_3c", "Slow Riff 3C")
    , ("slow_riff_3d", "Slow Riff 3D")
    , ("slow_riff_4", "Slow Riff 4")
    , ("slow_riff_4a", "Slow Riff 4A")
    , ("slow_riff_4b", "Slow Riff 4B")
    , ("slow_riff_4c", "Slow Riff 4C")
    , ("slow_riff_4d", "Slow Riff 4D")
    , ("swing_riff", "Swing Riff")
    , ("swing_riff_a", "Swing Riff A")
    , ("swing_riff_b", "Swing Riff B")
    , ("swing_riff_c", "Swing Riff C")
    , ("swing_riff_d", "Swing Riff D")
    , ("swing_riff_1", "Swing Riff 1")
    , ("swing_riff_1a", "Swing Riff 1A")
    , ("swing_riff_1b", "Swing Riff 1B")
    , ("swing_riff_1c", "Swing Riff 1C")
    , ("swing_riff_1d", "Swing Riff 1D")
    , ("swing_riff_2", "Swing Riff 2")
    , ("swing_riff_2a", "Swing Riff 2A")
    , ("swing_riff_2b", "Swing Riff 2B")
    , ("swing_riff_2c", "Swing Riff 2C")
    , ("swing_riff_2d", "Swing Riff 2D")
    , ("swing_riff_3", "Swing Riff 3")
    , ("swing_riff_3a", "Swing Riff 3A")
    , ("swing_riff_3b", "Swing Riff 3B")
    , ("swing_riff_3c", "Swing Riff 3C")
    , ("swing_riff_3d", "Swing Riff 3D")
    , ("swing_riff_4", "Swing Riff 4")
    , ("swing_riff_4a", "Swing Riff 4A")
    , ("swing_riff_4b", "Swing Riff 4B")
    , ("swing_riff_4c", "Swing Riff 4C")
    , ("swing_riff_4d", "Swing Riff 4D")
    , ("chunky_riff", "Chunky Riff")
    , ("chunky_riff_a", "Chunky Riff A")
    , ("chunky_riff_b", "Chunky Riff B")
    , ("chunky_riff_c", "Chunky Riff C")
    , ("chunky_riff_d", "Chunky Riff D")
    , ("chunky_riff_1", "Chunky Riff 1")
    , ("chunky_riff_1a", "Chunky Riff 1A")
    , ("chunky_riff_1b", "Chunky Riff 1B")
    , ("chunky_riff_1c", "Chunky Riff 1C")
    , ("chunky_riff_1d", "Chunky Riff 1D")
    , ("chunky_riff_2", "Chunky Riff 2")
    , ("chunky_riff_2a", "Chunky Riff 2A")
    , ("chunky_riff_2b", "Chunky Riff 2B")
    , ("chunky_riff_2c", "Chunky Riff 2C")
    , ("chunky_riff_2d", "Chunky Riff 2D")
    , ("chunky_riff_3", "Chunky Riff 3")
    , ("chunky_riff_3a", "Chunky Riff 3A")
    , ("chunky_riff_3b", "Chunky Riff 3B")
    , ("chunky_riff_3c", "Chunky Riff 3C")
    , ("chunky_riff_3d", "Chunky Riff 3D")
    , ("chunky_riff_4", "Chunky Riff 4")
    , ("chunky_riff_4a", "Chunky Riff 4A")
    , ("chunky_riff_4b", "Chunky Riff 4B")
    , ("chunky_riff_4c", "Chunky Riff 4C")
    , ("chunky_riff_4d", "Chunky Riff 4D")
    , ("odd_riff", "Odd Riff")
    , ("odd_riff_a", "Odd Riff A")
    , ("odd_riff_b", "Odd Riff B")
    , ("odd_riff_c", "Odd Riff C")
    , ("odd_riff_d", "Odd Riff D")
    , ("odd_riff_1", "Odd Riff 1")
    , ("odd_riff_1a", "Odd Riff 1A")
    , ("odd_riff_1b", "Odd Riff 1B")
    , ("odd_riff_1c", "Odd Riff 1C")
    , ("odd_riff_1d", "Odd Riff 1D")
    , ("odd_riff_2", "Odd Riff 2")
    , ("odd_riff_2a", "Odd Riff 2A")
    , ("odd_riff_2b", "Odd Riff 2B")
    , ("odd_riff_2c", "Odd Riff 2C")
    , ("odd_riff_2d", "Odd Riff 2D")
    , ("odd_riff_3", "Odd Riff 3")
    , ("odd_riff_3a", "Odd Riff 3A")
    , ("odd_riff_3b", "Odd Riff 3B")
    , ("odd_riff_3c", "Odd Riff 3C")
    , ("odd_riff_3d", "Odd Riff 3D")
    , ("odd_riff_4", "Odd Riff 4")
    , ("odd_riff_4a", "Odd Riff 4A")
    , ("odd_riff_4b", "Odd Riff 4B")
    , ("odd_riff_4c", "Odd Riff 4C")
    , ("odd_riff_4d", "Odd Riff 4D")
    , ("hook", "Hook")
    , ("hook_a", "Hook A")
    , ("hook_b", "Hook B")
    , ("hook_c", "Hook C")
    , ("hook_d", "Hook D")
    , ("hook_1", "Hook 1")
    , ("hook_1a", "Hook 1A")
    , ("hook_1b", "Hook 1B")
    , ("hook_1c", "Hook 1C")
    , ("hook_1d", "Hook 1D")
    , ("hook_2", "Hook 2")
    , ("hook_2a", "Hook 2A")
    , ("hook_2b", "Hook 2B")
    , ("hook_2c", "Hook 2C")
    , ("hook_2d", "Hook 2D")
    , ("hook_3", "Hook 3")
    , ("hook_3a", "Hook 3A")
    , ("hook_3b", "Hook 3B")
    , ("hook_3c", "Hook 3C")
    , ("hook_3d", "Hook 3D")
    , ("hook_4", "Hook 4")
    , ("hook_4a", "Hook 4A")
    , ("hook_4b", "Hook 4B")
    , ("hook_4c", "Hook 4C")
    , ("hook_4d", "Hook 4D")
    , ("drum_roll", "Drum Roll")
    , ("drum_roll_a", "Drum Roll A")
    , ("drum_roll_b", "Drum Roll B")
    , ("drum_roll_c", "Drum Roll C")
    , ("drum_roll_d", "Drum Roll D")
    , ("drum_roll_1", "Drum Roll 1")
    , ("drum_roll_1a", "Drum Roll 1A")
    , ("drum_roll_1b", "Drum Roll 1B")
    , ("drum_roll_1c", "Drum Roll 1C")
    , ("drum_roll_1d", "Drum Roll 1D")
    , ("drum_roll_2", "Drum Roll 2")
    , ("drum_roll_2a", "Drum Roll 2A")
    , ("drum_roll_2b", "Drum Roll 2B")
    , ("drum_roll_2c", "Drum Roll 2C")
    , ("drum_roll_2d", "Drum Roll 2D")
    , ("drum_roll_3", "Drum Roll 3")
    , ("drum_roll_3a", "Drum Roll 3A")
    , ("drum_roll_3b", "Drum Roll 3B")
    , ("drum_roll_3c", "Drum Roll 3C")
    , ("drum_roll_3d", "Drum Roll 3D")
    , ("drum_roll_4", "Drum Roll 4")
    , ("drum_roll_4a", "Drum Roll 4A")
    , ("drum_roll_4b", "Drum Roll 4B")
    , ("drum_roll_4c", "Drum Roll 4C")
    , ("drum_roll_4d", "Drum Roll 4D")
    , ("gtr_lead", "Gtr Lead")
    , ("gtr_lead_a", "Gtr Lead A")
    , ("gtr_lead_b", "Gtr Lead B")
    , ("gtr_lead_c", "Gtr Lead C")
    , ("gtr_lead_d", "Gtr Lead D")
    , ("gtr_lead_1", "Gtr Lead 1")
    , ("gtr_lead_1a", "Gtr Lead 1A")
    , ("gtr_lead_1b", "Gtr Lead 1B")
    , ("gtr_lead_1c", "Gtr Lead 1C")
    , ("gtr_lead_1d", "Gtr Lead 1D")
    , ("gtr_lead_2", "Gtr Lead 2")
    , ("gtr_lead_2a", "Gtr Lead 2A")
    , ("gtr_lead_2b", "Gtr Lead 2B")
    , ("gtr_lead_2c", "Gtr Lead 2C")
    , ("gtr_lead_2d", "Gtr Lead 2D")
    , ("gtr_lead_3", "Gtr Lead 3")
    , ("gtr_lead_3a", "Gtr Lead 3A")
    , ("gtr_lead_3b", "Gtr Lead 3B")
    , ("gtr_lead_3c", "Gtr Lead 3C")
    , ("gtr_lead_3d", "Gtr Lead 3D")
    , ("gtr_lead_4", "Gtr Lead 4")
    , ("gtr_lead_4a", "Gtr Lead 4A")
    , ("gtr_lead_4b", "Gtr Lead 4B")
    , ("gtr_lead_4c", "Gtr Lead 4C")
    , ("gtr_lead_4d", "Gtr Lead 4D")
    , ("gtr_fill", "Gtr Fill")
    , ("gtr_fill_a", "Gtr Fill A")
    , ("gtr_fill_b", "Gtr Fill B")
    , ("gtr_fill_c", "Gtr Fill C")
    , ("gtr_fill_d", "Gtr Fill D")
    , ("gtr_fill_1", "Gtr Fill 1")
    , ("gtr_fill_1a", "Gtr Fill 1A")
    , ("gtr_fill_1b", "Gtr Fill 1B")
    , ("gtr_fill_1c", "Gtr Fill 1C")
    , ("gtr_fill_1d", "Gtr Fill 1D")
    , ("gtr_fill_2", "Gtr Fill 2")
    , ("gtr_fill_2a", "Gtr Fill 2A")
    , ("gtr_fill_2b", "Gtr Fill 2B")
    , ("gtr_fill_2c", "Gtr Fill 2C")
    , ("gtr_fill_2d", "Gtr Fill 2D")
    , ("gtr_fill_3", "Gtr Fill 3")
    , ("gtr_fill_3a", "Gtr Fill 3A")
    , ("gtr_fill_3b", "Gtr Fill 3B")
    , ("gtr_fill_3c", "Gtr Fill 3C")
    , ("gtr_fill_3d", "Gtr Fill 3D")
    , ("gtr_fill_4", "Gtr Fill 4")
    , ("gtr_fill_4a", "Gtr Fill 4A")
    , ("gtr_fill_4b", "Gtr Fill 4B")
    , ("gtr_fill_4c", "Gtr Fill 4C")
    , ("gtr_fill_4d", "Gtr Fill 4D")
    , ("gtr_hook", "Gtr Hook")
    , ("gtr_hook_a", "Gtr Hook A")
    , ("gtr_hook_b", "Gtr Hook B")
    , ("gtr_hook_c", "Gtr Hook C")
    , ("gtr_hook_d", "Gtr Hook D")
    , ("gtr_hook_1", "Gtr Hook 1")
    , ("gtr_hook_1a", "Gtr Hook 1A")
    , ("gtr_hook_1b", "Gtr Hook 1B")
    , ("gtr_hook_1c", "Gtr Hook 1C")
    , ("gtr_hook_1d", "Gtr Hook 1D")
    , ("gtr_hook_2", "Gtr Hook 2")
    , ("gtr_hook_2a", "Gtr Hook 2A")
    , ("gtr_hook_2b", "Gtr Hook 2B")
    , ("gtr_hook_2c", "Gtr Hook 2C")
    , ("gtr_hook_2d", "Gtr Hook 2D")
    , ("gtr_hook_3", "Gtr Hook 3")
    , ("gtr_hook_3a", "Gtr Hook 3A")
    , ("gtr_hook_3b", "Gtr Hook 3B")
    , ("gtr_hook_3c", "Gtr Hook 3C")
    , ("gtr_hook_3d", "Gtr Hook 3D")
    , ("gtr_hook_4", "Gtr Hook 4")
    , ("gtr_hook_4a", "Gtr Hook 4A")
    , ("gtr_hook_4b", "Gtr Hook 4B")
    , ("gtr_hook_4c", "Gtr Hook 4C")
    , ("gtr_hook_4d", "Gtr Hook 4D")
    , ("gtr_melody", "Gtr Melody")
    , ("gtr_melody_a", "Gtr Melody A")
    , ("gtr_melody_b", "Gtr Melody B")
    , ("gtr_melody_c", "Gtr Melody C")
    , ("gtr_melody_d", "Gtr Melody D")
    , ("gtr_melody_1", "Gtr Melody 1")
    , ("gtr_melody_1a", "Gtr Melody 1A")
    , ("gtr_melody_1b", "Gtr Melody 1B")
    , ("gtr_melody_1c", "Gtr Melody 1C")
    , ("gtr_melody_1d", "Gtr Melody 1D")
    , ("gtr_melody_2", "Gtr Melody 2")
    , ("gtr_melody_2a", "Gtr Melody 2A")
    , ("gtr_melody_2b", "Gtr Melody 2B")
    , ("gtr_melody_2c", "Gtr Melody 2C")
    , ("gtr_melody_2d", "Gtr Melody 2D")
    , ("gtr_melody_3", "Gtr Melody 3")
    , ("gtr_melody_3a", "Gtr Melody 3A")
    , ("gtr_melody_3b", "Gtr Melody 3B")
    , ("gtr_melody_3c", "Gtr Melody 3C")
    , ("gtr_melody_3d", "Gtr Melody 3D")
    , ("gtr_melody_4", "Gtr Melody 4")
    , ("gtr_melody_4a", "Gtr Melody 4A")
    , ("gtr_melody_4b", "Gtr Melody 4B")
    , ("gtr_melody_4c", "Gtr Melody 4C")
    , ("gtr_melody_4d", "Gtr Melody 4D")
    , ("gtr_line", "Gtr Line")
    , ("gtr_line_a", "Gtr Line A")
    , ("gtr_line_b", "Gtr Line B")
    , ("gtr_line_c", "Gtr Line C")
    , ("gtr_line_d", "Gtr Line D")
    , ("gtr_line_1", "Gtr Line 1")
    , ("gtr_line_1a", "Gtr Line 1A")
    , ("gtr_line_1b", "Gtr Line 1B")
    , ("gtr_line_1c", "Gtr Line 1C")
    , ("gtr_line_1d", "Gtr Line 1D")
    , ("gtr_line_2", "Gtr Line 2")
    , ("gtr_line_2a", "Gtr Line 2A")
    , ("gtr_line_2b", "Gtr Line 2B")
    , ("gtr_line_2c", "Gtr Line 2C")
    , ("gtr_line_2d", "Gtr Line 2D")
    , ("gtr_line_3", "Gtr Line 3")
    , ("gtr_line_3a", "Gtr Line 3A")
    , ("gtr_line_3b", "Gtr Line 3B")
    , ("gtr_line_3c", "Gtr Line 3C")
    , ("gtr_line_3d", "Gtr Line 3D")
    , ("gtr_line_4", "Gtr Line 4")
    , ("gtr_line_4a", "Gtr Line 4A")
    , ("gtr_line_4b", "Gtr Line 4B")
    , ("gtr_line_4c", "Gtr Line 4C")
    , ("gtr_line_4d", "Gtr Line 4D")
    , ("gtr_lick", "Gtr Lick")
    , ("gtr_lick_a", "Gtr Lick A")
    , ("gtr_lick_b", "Gtr Lick B")
    , ("gtr_lick_c", "Gtr Lick C")
    , ("gtr_lick_d", "Gtr Lick D")
    , ("gtr_lick_1", "Gtr Lick 1")
    , ("gtr_lick_1a", "Gtr Lick 1A")
    , ("gtr_lick_1b", "Gtr Lick 1B")
    , ("gtr_lick_1c", "Gtr Lick 1C")
    , ("gtr_lick_1d", "Gtr Lick 1D")
    , ("gtr_lick_2", "Gtr Lick 2")
    , ("gtr_lick_2a", "Gtr Lick 2A")
    , ("gtr_lick_2b", "Gtr Lick 2B")
    , ("gtr_lick_2c", "Gtr Lick 2C")
    , ("gtr_lick_2d", "Gtr Lick 2D")
    , ("gtr_lick_3", "Gtr Lick 3")
    , ("gtr_lick_3a", "Gtr Lick 3A")
    , ("gtr_lick_3b", "Gtr Lick 3B")
    , ("gtr_lick_3c", "Gtr Lick 3C")
    , ("gtr_lick_3d", "Gtr Lick 3D")
    , ("gtr_lick_4", "Gtr Lick 4")
    , ("gtr_lick_4a", "Gtr Lick 4A")
    , ("gtr_lick_4b", "Gtr Lick 4B")
    , ("gtr_lick_4c", "Gtr Lick 4C")
    , ("gtr_lick_4d", "Gtr Lick 4D")
    , ("vocal_break", "Vocal Break")
    , ("vocal_break_a", "Vocal Break A")
    , ("vocal_break_b", "Vocal Break B")
    , ("vocal_break_c", "Vocal Break C")
    , ("vocal_break_d", "Vocal Break D")
    , ("vocal_break_1", "Vocal Break 1")
    , ("vocal_break_1a", "Vocal Break 1A")
    , ("vocal_break_1b", "Vocal Break 1B")
    , ("vocal_break_1c", "Vocal Break 1C")
    , ("vocal_break_1d", "Vocal Break 1D")
    , ("vocal_break_2", "Vocal Break 2")
    , ("vocal_break_2a", "Vocal Break 2A")
    , ("vocal_break_2b", "Vocal Break 2B")
    , ("vocal_break_2c", "Vocal Break 2C")
    , ("vocal_break_2d", "Vocal Break 2D")
    , ("vocal_break_3", "Vocal Break 3")
    , ("vocal_break_3a", "Vocal Break 3A")
    , ("vocal_break_3b", "Vocal Break 3B")
    , ("vocal_break_3c", "Vocal Break 3C")
    , ("vocal_break_3d", "Vocal Break 3D")
    , ("vocal_break_4", "Vocal Break 4")
    , ("vocal_break_4a", "Vocal Break 4A")
    , ("vocal_break_4b", "Vocal Break 4B")
    , ("vocal_break_4c", "Vocal Break 4C")
    , ("vocal_break_4d", "Vocal Break 4D")
    , ("ah", "Ah!")
    , ("yeah", "Yeah!")
    , ("oohs", "Oohs and Ahs")
    , ("oohs_a", "Oohs and Ahs A")
    , ("oohs_b", "Oohs and Ahs B")
    , ("oohs_c", "Oohs and Ahs C")
    , ("oohs_d", "Oohs and Ahs D")
    , ("oohs_1", "Oohs and Ahs 1")
    , ("oohs_1a", "Oohs and Ahs 1A")
    , ("oohs_1b", "Oohs and Ahs 1B")
    , ("oohs_1c", "Oohs and Ahs 1C")
    , ("oohs_1d", "Oohs and Ahs 1D")
    , ("oohs_2", "Oohs and Ahs 2")
    , ("oohs_2a", "Oohs and Ahs 2A")
    , ("oohs_2b", "Oohs and Ahs 2B")
    , ("oohs_2c", "Oohs and Ahs 2C")
    , ("oohs_2d", "Oohs and Ahs 2D")
    , ("oohs_3", "Oohs and Ahs 3")
    , ("oohs_3a", "Oohs and Ahs 3A")
    , ("oohs_3b", "Oohs and Ahs 3B")
    , ("oohs_3c", "Oohs and Ahs 3C")
    , ("oohs_3d", "Oohs and Ahs 3D")
    , ("oohs_4", "Oohs and Ahs 4")
    , ("oohs_4a", "Oohs and Ahs 4A")
    , ("oohs_4b", "Oohs and Ahs 4B")
    , ("oohs_4c", "Oohs and Ahs 4C")
    , ("oohs_4d", "Oohs and Ahs 4D")
    , ("prayer", "Prayer")
    , ("prayer_a", "Prayer A")
    , ("prayer_b", "Prayer B")
    , ("prayer_c", "Prayer C")
    , ("prayer_d", "Prayer D")
    , ("prayer_1", "Prayer 1")
    , ("prayer_1a", "Prayer 1A")
    , ("prayer_1b", "Prayer 1B")
    , ("prayer_1c", "Prayer 1C")
    , ("prayer_1d", "Prayer 1D")
    , ("prayer_2", "Prayer 2")
    , ("prayer_2a", "Prayer 2A")
    , ("prayer_2b", "Prayer 2B")
    , ("prayer_2c", "Prayer 2C")
    , ("prayer_2d", "Prayer 2D")
    , ("prayer_3", "Prayer 3")
    , ("prayer_3a", "Prayer 3A")
    , ("prayer_3b", "Prayer 3B")
    , ("prayer_3c", "Prayer 3C")
    , ("prayer_3d", "Prayer 3D")
    , ("prayer_4", "Prayer 4")
    , ("prayer_4a", "Prayer 4A")
    , ("prayer_4b", "Prayer 4B")
    , ("prayer_4c", "Prayer 4C")
    , ("prayer_4d", "Prayer 4D")
    , ("chant", "Chant")
    , ("chant_a", "Chant A")
    , ("chant_b", "Chant B")
    , ("chant_c", "Chant C")
    , ("chant_d", "Chant D")
    , ("chant_1", "Chant 1")
    , ("chant_1a", "Chant 1A")
    , ("chant_1b", "Chant 1B")
    , ("chant_1c", "Chant 1C")
    , ("chant_1d", "Chant 1D")
    , ("chant_2", "Chant 2")
    , ("chant_2a", "Chant 2A")
    , ("chant_2b", "Chant 2B")
    , ("chant_2c", "Chant 2C")
    , ("chant_2d", "Chant 2D")
    , ("chant_3", "Chant 3")
    , ("chant_3a", "Chant 3A")
    , ("chant_3b", "Chant 3B")
    , ("chant_3c", "Chant 3C")
    , ("chant_3d", "Chant 3D")
    , ("chant_4", "Chant 4")
    , ("chant_4a", "Chant 4A")
    , ("chant_4b", "Chant 4B")
    , ("chant_4c", "Chant 4C")
    , ("chant_4d", "Chant 4D")
    , ("spoken_word", "Spoken Word")
    , ("spoken_word_a", "Spoken Word A")
    , ("spoken_word_b", "Spoken Word B")
    , ("spoken_word_c", "Spoken Word C")
    , ("spoken_word_d", "Spoken Word D")
    , ("spoken_word_1", "Spoken Word 1")
    , ("spoken_word_1a", "Spoken Word 1A")
    , ("spoken_word_1b", "Spoken Word 1B")
    , ("spoken_word_1c", "Spoken Word 1C")
    , ("spoken_word_1d", "Spoken Word 1D")
    , ("spoken_word_2", "Spoken Word 2")
    , ("spoken_word_2a", "Spoken Word 2A")
    , ("spoken_word_2b", "Spoken Word 2B")
    , ("spoken_word_2c", "Spoken Word 2C")
    , ("spoken_word_2d", "Spoken Word 2D")
    , ("spoken_word_3", "Spoken Word 3")
    , ("spoken_word_3a", "Spoken Word 3A")
    , ("spoken_word_3b", "Spoken Word 3B")
    , ("spoken_word_3c", "Spoken Word 3C")
    , ("spoken_word_3d", "Spoken Word 3D")
    , ("spoken_word_4", "Spoken Word 4")
    , ("spoken_word_4a", "Spoken Word 4A")
    , ("spoken_word_4b", "Spoken Word 4B")
    , ("spoken_word_4c", "Spoken Word 4C")
    , ("spoken_word_4d", "Spoken Word 4D")
    , ("outro", "Outro")
    , ("outro_a", "Outro A")
    , ("outro_b", "Outro B")
    , ("outro_c", "Outro C")
    , ("outro_d", "Outro D")
    , ("outro_1", "Outro 1")
    , ("outro_1a", "Outro 1A")
    , ("outro_1b", "Outro 1B")
    , ("outro_1c", "Outro 1C")
    , ("outro_1d", "Outro 1D")
    , ("outro_2", "Outro 2")
    , ("outro_2a", "Outro 2A")
    , ("outro_2b", "Outro 2B")
    , ("outro_2c", "Outro 2C")
    , ("outro_2d", "Outro 2D")
    , ("outro_3", "Outro 3")
    , ("outro_3a", "Outro 3A")
    , ("outro_3b", "Outro 3B")
    , ("outro_3c", "Outro 3C")
    , ("outro_3d", "Outro 3D")
    , ("outro_4", "Outro 4")
    , ("outro_4a", "Outro 4A")
    , ("outro_4b", "Outro 4B")
    , ("outro_4c", "Outro 4C")
    , ("outro_4d", "Outro 4D")
    , ("outro_solo", "Outro Solo")
    , ("outro_solo_a", "Outro Solo A")
    , ("outro_solo_b", "Outro Solo B")
    , ("outro_solo_c", "Outro Solo C")
    , ("outro_solo_d", "Outro Solo D")
    , ("outro_chorus", "Outro Chorus")
    , ("outro_chorus_a", "Outro Chorus A")
    , ("outro_chorus_b", "Outro Chorus B")
    , ("outro_chorus_c", "Outro Chorus C")
    , ("outro_chorus_d", "Outro Chorus D")
    , ("ending", "Ending")
    , ("ending_a", "Ending A")
    , ("ending_b", "Ending B")
    , ("ending_c", "Ending C")
    , ("ending_d", "Ending D")
    , ("bre", "Big Rock Ending!")
    , ("fade_out", "Fade Out")
    , ("fade_out_a", "Fade Out A")
    , ("fade_out_b", "Fade Out B")
    , ("fade_out_c", "Fade Out C")
    , ("fade_out_d", "Fade Out D")
    , ("a", "A Section")
    , ("a1", "A Section 1")
    , ("a2", "A Section 2")
    , ("a3", "A Section 3")
    , ("a4", "A Section 4")
    , ("a5", "A Section 5")
    , ("a6", "A Section 6")
    , ("a7", "A Section 7")
    , ("a8", "A Section 8")
    , ("a9", "A Section 9")
    , ("b", "B Section")
    , ("b1", "B Section 1")
    , ("b2", "B Section 2")
    , ("b3", "B Section 3")
    , ("b4", "B Section 4")
    , ("b5", "B Section 5")
    , ("b6", "B Section 6")
    , ("b7", "B Section 7")
    , ("b8", "B Section 8")
    , ("b9", "B Section 9")
    , ("c", "C Section")
    , ("c1", "C Section 1")
    , ("c2", "C Section 2")
    , ("c3", "C Section 3")
    , ("c4", "C Section 4")
    , ("c5", "C Section 5")
    , ("c6", "C Section 6")
    , ("c7", "C Section 7")
    , ("c8", "C Section 8")
    , ("c9", "C Section 9")
    , ("d", "D Section")
    , ("d1", "D Section 1")
    , ("d2", "D Section 2")
    , ("d3", "D Section 3")
    , ("d4", "D Section 4")
    , ("d5", "D Section 5")
    , ("d6", "D Section 6")
    , ("d7", "D Section 7")
    , ("d8", "D Section 8")
    , ("d9", "D Section 9")
    , ("e", "E Section")
    , ("e1", "E Section 1")
    , ("e2", "E Section 2")
    , ("e3", "E Section 3")
    , ("e4", "E Section 4")
    , ("e5", "E Section 5")
    , ("e6", "E Section 6")
    , ("e7", "E Section 7")
    , ("e8", "E Section 8")
    , ("e9", "E Section 9")
    , ("f", "F Section")
    , ("f1", "F Section 1")
    , ("f2", "F Section 2")
    , ("f3", "F Section 3")
    , ("f4", "F Section 4")
    , ("f5", "F Section 5")
    , ("f6", "F Section 6")
    , ("f7", "F Section 7")
    , ("f8", "F Section 8")
    , ("f9", "F Section 9")
    , ("g", "G Section")
    , ("g1", "G Section 1")
    , ("g2", "G Section 2")
    , ("g3", "G Section 3")
    , ("g4", "G Section 4")
    , ("g5", "G Section 5")
    , ("g6", "G Section 6")
    , ("g7", "G Section 7")
    , ("g8", "G Section 8")
    , ("g9", "G Section 9")
    , ("h", "H Section")
    , ("h1", "H Section 1")
    , ("h2", "H Section 2")
    , ("h3", "H Section 3")
    , ("h4", "H Section 4")
    , ("h5", "H Section 5")
    , ("h6", "H Section 6")
    , ("h7", "H Section 7")
    , ("h8", "H Section 8")
    , ("h9", "H Section 9")
    , ("i", "I Section")
    , ("i1", "I Section 1")
    , ("i2", "I Section 2")
    , ("i3", "I Section 3")
    , ("i4", "I Section 4")
    , ("i5", "I Section 5")
    , ("i6", "I Section 6")
    , ("i7", "I Section 7")
    , ("i8", "I Section 8")
    , ("i9", "I Section 9")
    , ("j", "J Section")
    , ("j1", "J Section 1")
    , ("j2", "J Section 2")
    , ("j3", "J Section 3")
    , ("j4", "J Section 4")
    , ("j5", "J Section 5")
    , ("j6", "J Section 6")
    , ("j7", "J Section 7")
    , ("j8", "J Section 8")
    , ("j9", "J Section 9")
    , ("k", "K Section")
    , ("k1", "K Section 1")
    , ("k2", "K Section 2")
    , ("k3", "K Section 3")
    , ("k4", "K Section 4")
    , ("k5", "K Section 5")
    , ("k6", "K Section 6")
    , ("k7", "K Section 7")
    , ("k8", "K Section 8")
    , ("k9", "K Section 9")
    , ("ugc_section_20_0", "0%-20%")
    , ("ugc_section_20_20", "20%-40%")
    , ("ugc_section_20_40", "40%-60%")
    , ("ugc_section_20_60", "60%-80%")
    , ("ugc_section_20_80", "80%-100%")
    , ("ugc_section_10_0", "0%-10%")
    , ("ugc_section_10_10", "10%-20%")
    , ("ugc_section_10_20", "20%-30%")
    , ("ugc_section_10_30", "30%-40%")
    , ("ugc_section_10_40", "40%-50%")
    , ("ugc_section_10_50", "50%-60%")
    , ("ugc_section_10_60", "60%-70%")
    , ("ugc_section_10_70", "70%-80%")
    , ("ugc_section_10_80", "80%-90%")
    , ("ugc_section_10_90", "90%-100%")
    , ("ugc_section_5_0", "0%-5%")
    , ("ugc_section_5_5", "5%-10%")
    , ("ugc_section_5_10", "10%-15%")
    , ("ugc_section_5_15", "15%-20%")
    , ("ugc_section_5_20", "20%-25%")
    , ("ugc_section_5_25", "25%-30%")
    , ("ugc_section_5_30", "30%-35%")
    , ("ugc_section_5_35", "35%-40%")
    , ("ugc_section_5_40", "40%-45%")
    , ("ugc_section_5_45", "45%-50%")
    , ("ugc_section_5_50", "50%-55%")
    , ("ugc_section_5_55", "55%-60%")
    , ("ugc_section_5_60", "60%-65%")
    , ("ugc_section_5_65", "65%-70%")
    , ("ugc_section_5_70", "70%-75%")
    , ("ugc_section_5_75", "75%-80%")
    , ("ugc_section_5_80", "80%-85%")
    , ("ugc_section_5_85", "85%-90%")
    , ("ugc_section_5_90", "90%-95%")
    , ("ugc_section_5_95", "95%-100%")
    ]

  in HM.fromList $ rbn2Sections >>= \(k, v) ->
    [ (sectionLookupForm k, (k, v))
    , (sectionLookupForm v, (k, v))
    ]

sectionLookupForm :: T.Text -> T.Text
sectionLookupForm = T.replace "guitar" "gtr" . T.filter isAlphaNum . T.toLower

findRBN2Section :: T.Text -> Maybe (T.Text, T.Text)
findRBN2Section = (`HM.lookup` rbn2LookupTable) . sectionLookupForm
