#!/usr/bin/env ruby

require 'fileutils'
require 'yaml'

def system_(*args)
  STDERR.puts args.join(' ')
  result = system(*args)
  raise(IOError, "Command returned #{$?.exitstatus}") unless result
end

dash = ARGV.index { |s| s.start_with? '--' } || ARGV.length
if dash < 2
  STDERR.puts "Usage: #{$0} path/to/song1 [path/to/song2 ...] /Volumes/MyUSBDrive/ [--options]"
  exit 1
end
songs = ARGV[0 .. dash - 2]
usb = ARGV[dash - 1]
options = ARGV[dash .. -1]

rb3 = "#{usb}/Content/0000000000000000/45410914/00000001"
FileUtils.mkdir_p rb3

class String
  def javahash
    self.chars.each_with_index.map do |c, i|
      c.ord * 31 ** (self.length - (i + 1) )
    end.inject(:+)
  end
end

songs.each do |song|
  p song
  con_title = YAML.load_file("#{song}/song.yml")['metadata']['title'].gsub(/[^A-Za-z0-9]/, '') + '_' + (song.javahash % 10000).to_s
  # try plans, multitrack ones first
  successful = nil
  ['jammit', 'pledgemusic', 'drumcam', 'album'].each do |plan|
    begin
      system_ "onyxbuild --song #{song}/song.yml gen/plan/#{plan}/2p/rb3.con #{options.join(' ')}"
      successful = plan
    rescue IOError
      # not successful, try next plan
    end
    break if successful
  end
  if successful
    FileUtils.cp "#{song}/gen/plan/#{successful}/2p/rb3.con", "#{rb3}/#{con_title}"
  else
    STDERR.puts "Failed to build song #{song}"
    exit 1
  end
end
