#!/usr/bin/env ruby

require 'yaml'

def system_(*args)
  STDERR.puts args.join(' ')
  result = system(*args)
  raise(IOError, "Command returned #{$?.exitstatus}") if result != true
end

yamls = Dir['songs/*/*/song.yml']
yamls.each do |yaml_file|
  folder = File.dirname(yaml_file)
  puts ">>> SONG: #{folder}"
  yaml = YAML.load_file(yaml_file)
  next unless yaml.fetch('published', true)
  audio = yaml['plans'].keys
  makes = []
  audio.each do |a|
    ['1p', '2p'].each do |p|
      makes += [
        "gen/plan/#{a}/countin.wav",
        "gen/plan/#{a}/#{p}/magma/magma.rbproj",
        "gen/plan/#{a}/#{p}/magma/notes.mid",
        "gen/plan/#{a}/#{p}/magma/cover.bmp",
      ]
      plan_exprs = yaml['plans'][a]
      unless plan_exprs.has_key?('each')
        # we need to make dummy audio for instruments not present
        yaml['instruments'].each_key do |inst|
          makes += ["gen/plan/#{a}/#{p}/magma/#{inst}.wav"] unless plan_exprs.has_key?(inst)
        end
      end
    end
  end
  Dir.chdir(folder) do
    system_("onyxbuild", "-q", *makes)
  end
end
