#!/bin/bash

# Gets rid of files not needed in the Magma distribution.

rm -rf */*/notes.mid
rm -rf */*/gen/cover.bmp
rm -rf */*/gen/cover.bmp
rm -rf */*/gen/*/notes.mid
rm -rf */*/gen/*/{1p,2p}/notes.mid
rm -rf */*/gen/*/{1p,2p}/{drums,bass}.wav
rm -rf */*/*.rar
rm -rf */*/*.txt
rm -rf */*/tempo-*.mid
rm -rf albums/ covers/ sound/ test/ scripts/
