#!/usr/bin/env ruby

# Deletes any song folders that don't have a README.md

require 'fileutils'

artists = %w{
  bad-salad
  danimal-cannon
  dream-theater
  haken
  john-petrucci
  jordan-rudess
  liquid-tension-experiment
  mahavishnu-orchestra
  maximum-the-hormone
  opeth
  soil-and-pimp-sessions
  toe
  yoshida-brothers
  youngblood-brass-band
}
artists.each do |art|
  Dir["#{art}/*/"].each do |song|
    unless File.exist?("#{song}/README.md")
      puts song
      FileUtils.rm_rf(song)
    end
  end
  if Dir["#{art}/*/"].empty?
    FileUtils.rm_rf(art)
  end
end
