#!/usr/bin/env ruby

# given a midi and a sound clip, make a new file which has a copy
# of the sound clip at every position where there is a text event "countin_here"
# in the midi.

require 'tmpdir'

if ARGV.length != 3
  STDERR.puts "Usage: #{$0} source.mid sound.wav out.wav"
  exit 1
end
mid, wav, out = ARGV

str = `midiscript -s "#{mid}" -`

countin_regex = / \b (\d+ \. \d+) s: [^;]*? text \s+ "countin_here" /mx
secs = str.scan(countin_regex).map { |grps| grps[0] }

case secs.length
when 0
  STDERR.puts "Warning: no countin events found in #{mid}"
  `sox "#{wav}" "#{out}" pad 1 trim 0 1`
when 1
  `sox "#{wav}" "#{out}" pad #{secs[0]}`
else
  Dir.mktmpdir do |d|
    files = []
    secs.each do |sec|
      file = "#{d}/#{sec}.wav"
      `sox "#{wav}" "#{file}" pad #{sec}`
      files << file
    end
    `sox --combine mix -v 1 #{files.map(&:inspect).join(' ')} "#{out}"`
  end
end

