#!/usr/bin/env ruby

# prints the time in seconds of each occurrence of a given text event.

if ARGV.length != 2
  STDERR.puts "Usage: #{$0} search-string notes.mid"
  exit 1
end
search, mid = ARGV

str = `midiscript -s "#{mid}" -`

escaped = Regexp.escape(search)
regex = / \b (\d+ \. \d+) s: [^;]*? text \s+ "#{escaped}" /mx
secs = str.scan(regex).map { |grps| grps[0] }
if secs.empty?
  STDERR.puts "Warning: no matches for event #{search}"
else
  secs.each { |s| puts s }
end
