#!/usr/bin/env ruby

# meant to be ran from the repository root.
# copies all generated con files to a new folder, named by song.

require 'fileutils'
FileUtils::mkdir_p 'cons'

cons = Dir['songs/*/*/gen/*/*/rb3.con']
cons.each do |con|
  con.match(/ \/ ([^\/]+) \/ gen \/ /x) do |md|
    `cp #{con} cons/#{md[1]}.con`
  end
end
