#!/usr/bin/env ruby

require 'fileutils'

if ARGV.length != 1
  throw "Usage #{$0} .../notes.mid"
end
mid = ARGV[0]

`onyx mt "#{mid}" "#{mid}.txt" --measure`
s = File.read("#{mid}.txt")
FileUtils.rm("#{mid}.txt")
s.match(/"countin" ch 0 \{([^\}]*)\}/) do |md|
  File.write("#{mid}.countin.txt", "
  hihat:
    path: ../../../sound/hihat-foot.wav
plans:
  album:
    countin:" + md[1].gsub('text "countin_here";', 'hihat').gsub('  ', '      ').rstrip)
end
