#!/usr/bin/env ruby

# stick the cs-hosted preview link in each song readme
Dir["songs/*/*/README.md"].each do |readme|
  readme.match(/^songs\/([\w-]+)\/([\w-]+)\/README.md$/) do |md|
    artist = md[1]
    title = md[2]
    s = File.read "songs/#{artist}/#{title}/README.md"
    s.gsub!('* (Pro) Drums: Expert', "* (Pro) Drums: Expert
    [(preview)](http://pages.cs.wisc.edu/~tolly/customs/?artist=#{artist}&title=#{title})")
    File.write "songs/#{artist}/#{title}/README.md", s
  end
end
