#!/usr/bin/env ruby

require_relative 'common'

if ARGV.length < 1
  STDERR.puts "Usage: #{$0} path/to/song/ [--audio dir/]"
  exit 1
end
song = ARGV[0]

Dir.chdir(song) do
  system_(*%w{onyx build gen/plan/album/2p/notes.mid gen/plan/album/song-countin.ogg}, *(ARGV[1..-1]))
end
Dir.chdir('haskell/preview') do
  system_(*%w{stack exec onyxpreview}, "../../#{song}")
end
