#!/usr/bin/env fish

set audiodir $argv[1]
if test -z $audiodir
  exit 1
end

set songdirs
for readme in songs/*/*/README.md
  set songdirs $songdirs (dirname $readme)
end
scripts/copy-audio $audiodir $songdirs
scripts/preview-deploy $songdirs
