#!/usr/bin/env ruby

require_relative 'common'

Dir['songs*/*/*/song.yml'].each do |f|
  yaml = load_yaml_tree f
  next unless yaml.fetch('published', true)
  puts f
  system('onyx', 'build', '--song', f, 'gen/plan/album/2p/problems')
end
