#!/usr/bin/env ruby

# turn a RB3 dta rank value into a tier from 1 to 7.

$cutoffs = {
  drums:       [124, 151, 178, 242, 345, 448],
  vocals:      [132, 175, 218, 279, 353, 427],
  bass:        [135, 181, 228, 293, 364, 436],
  guitar:      [139, 176, 221, 267, 333, 409],
  keys:        [153, 211, 269, 327, 385, 443],
  real_guitar: [150, 205, 264, 323, 382, 442],
  real_bass:   [150, 208, 267, 325, 384, 442],
  band:        [163, 215, 243, 267, 292, 345],
}
$cutoffs[:real_keys] = $cutoffs[:keys]

def print_usage
  STDERR.puts "Usage: #{$0} instrument rank"
  STDERR.puts "  Instruments:"
  STDERR.puts $cutoffs.keys.join(', ')
  exit 1
end

if ARGV.length != 2
  print_usage
end
inst, rank = ARGV
inst = inst.to_sym
unless $cutoffs.has_key? inst
  STDERR.puts "Instrument not recognized: #{inst}"
  print_usage
end
unless rank.match /^\d+$/m
  STDERR.puts "Not a valid rank number: #{rank}"
  print_usage
end
rank = rank.to_i

puts 1 + $cutoffs[inst].count { |cut| cut <= rank }
