#!/usr/bin/env ruby

# Remakes all the GitHub README.md files for the song directories.

require_relative 'common'

system_ "rm -rf songs/*/*/README.md"
Dir['songs/*/*/song.yml'].each do |f|
  yaml = load_yaml_tree(f)
  next unless yaml.fetch('published', true)
  system_ "onyxbuild README.md --song #{f}"
end
