#!/bin/bash
set -e
set -u

file_in=`mktemp -u audio-XXXXXXXX.m4a`
file_out=${3:-audio-youtube.wav}

youtube-dl "https://www.youtube.com/watch?v=$1" -f "$2" -o "$file_in"
rm -f "$file_out"
ffmpeg -i "$file_in" "$file_out"
rm -f "$file_in"
