title = Hell's Kitchen
package = hellskitchen
cover-name = falling-into-infinity
number = 6
album-pad = 5.051
next-cutoff = 5.696
album-fadeout = 4.500

album-config = double
include ../../make/config/drums.mk
