title = Sacrificed Sons
package = sacrificedsons
cover-name = octavarium
number = 7
jammit-trim = 46.526
album-trim = 45.914
fadein = 6.866
jammit-fadein = $(fadein)
album-fadein  = $(fadein)

include ../../make/config/drums.mk
