title = Lines in the Sand
package = linesinthesand
cover-name = falling-into-infinity
number = 7
jammit-trim = 2.222
jammit-fadein = 4.180
jammit-pad = 2.849
album-fadein = 4.261
album-pad = 2.768

include ../../make/config/drums.mk
