title = Metropolis, Pt. 1: The Miracle and the Sleeper
jammit-title = Metropolis Pt. 1
package = metropolispt1
cover-name = images-and-words
number = 5
album-trim = 0.379

include ../../make/config/drums.mk
